export type AmaBsaSystem = 'AMA EL' | 'BSAB 96' | 'AMA Samordning';

export interface AmaBsaEntry {
  code: string;
  system: AmaBsaSystem;
  title: string;
  category: string;
  parentCode?: string;
  scope: string;
  typicalMaterials: string[];
  iec81346Equivalents?: string[];
  iec61355Documents?: string[];
  raNotes?: string;
}

export const AMA_BSA_CATEGORIES = [
  'Alla',
  'Kanalisation & Förläggning',
  'Kablar & Ledningar',
  'Centraler, Ställverk & Skåp',
  'Kraftförsörjning, Reservkraft & Solceller',
  'Installationsapparater & Uttag',
  'Belysning & Belysningsstyrning',
  'Drivsystem, Motorer & Kraftuttag',
  'Jordning, Åskskydd & Potentialutjämning',
  'Tele, Data & Fastighetsnät',
  'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
  'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
  'Transportsystem (Hissar m.m.)',
  'Märkning, Provning & Dokumentation (Y)',
] as const;

export const AMA_BSA_ENTRIES: AmaBsaEntry[] = [
  // ==========================================
  // BSAB 96 BYGGDELSKODER (KAPITEL 6 EL & TELE)
  // ==========================================
  {
    code: '60',
    system: 'BSAB 96',
    title: 'El- och telesystem (övergripande)',
    category: 'Centraler, Ställverk & Skåp',
    scope: 'Övergripande sammansatt redovisning av el- och teleanläggningar för byggnad eller anläggning.',
    typicalMaterials: ['Samordnad handling', 'Gränsdragningslista', 'Teknisk beskrivning'],
    iec81346Equivalents: ['=W', '=E'],
    iec61355Documents: ['&AA', '&BA'],
    raNotes: 'Används som samlingsrubrik i rambeskrivningar och systemhandlingar vid tidiga projekteringsskeden.',
  },
  {
    code: '61',
    system: 'BSAB 96',
    title: 'El- och telekanalisation',
    category: 'Kanalisation & Förläggning',
    scope: 'System för förläggning och skydd av elkablar, tele- och dataledningar i mark och byggnad.',
    typicalMaterials: ['Kabelstegar', 'Trådstegar', 'Installationsrör', 'Kabelrännor', 'Kanaler'],
    iec81346Equivalents: ['+W', '+C'],
    iec61355Documents: ['&FN', '&FL'],
    raNotes: 'Samordnas med VS- och ventilationsstråk för att undvika kollisioner i korridorer och schakt.',
  },
  {
    code: '61.1',
    system: 'BSAB 96',
    title: 'Kanalisation i mark och utomhus',
    category: 'Kanalisation & Förläggning',
    parentCode: '61',
    scope: 'Kabelskyddsrör, kabelbrunnar, markeringsband och kulvertar förläggs i schakt utomhus.',
    typicalMaterials: ['Kabelskyddsrör SRN/SRS', 'Kabelbrunnar av betong/plast', 'Gul varningsremsa', 'Skarvmuffar'],
    iec81346Equivalents: ['+G', '+U'],
    iec61355Documents: ['&FN', '&PL'],
    raNotes: 'Minimiförläggningsdjup enligt EBR-krav (normalt 0,65 m i mark, 0,35 m under platta/hårdgjord yta).',
  },
  {
    code: '61.2',
    system: 'BSAB 96',
    title: 'Bärande förläggningsmateriel i byggnad',
    category: 'Kanalisation & Förläggning',
    parentCode: '61',
    scope: 'Horisontella och vertikala bärverk för kablar i tak, bjälklag och schakt.',
    typicalMaterials: ['Kabelstegar (förzinkade/syrafasta)', 'Trådstegar', 'Pendelskenor', 'Konsoler', 'Armaturskenor'],
    iec81346Equivalents: ['+W'],
    iec61355Documents: ['&FN'],
    raNotes: 'Dimensioneras med minst 20-30 % reservkapacitet för framtida kablage och kabellast.',
  },
  {
    code: '61.3',
    system: 'BSAB 96',
    title: 'Installationskanaler och fönsterbänkskanaler',
    category: 'Kanalisation & Förläggning',
    parentCode: '61',
    scope: 'Ytmonterade kanalsystem på vägg i kontor, skolor och arbetsplatser.',
    typicalMaterials: ['Fönsterbänkskanaler i aluminium/plast', 'Minikanaler', 'Hörnkanaler', 'Skiljeväggar starkström/svagström'],
    iec81346Equivalents: ['+W', '+R'],
    iec61355Documents: ['&FN'],
    raNotes: 'Skiljevägg krävs för att separera starkströmsledningar från tele/data (EMC-krav).',
  },
  {
    code: '61.4',
    system: 'BSAB 96',
    title: 'Golvkanalsystem och installationsgolv',
    category: 'Kanalisation & Förläggning',
    parentCode: '61',
    scope: 'Ingjutna golvkanaler, installationsgolv och golvboxar för flexibla kontorsmiljöer.',
    typicalMaterials: ['Ingjutningskanaler', 'Uttagsboxar för golv', 'Hålrumsgolv med inspektionsluckor'],
    iec81346Equivalents: ['+W', '+F'],
    iec61355Documents: ['&FN'],
    raNotes: 'Viktigt att samordna med gjutning och golvbeläggning (parkett, matta, klinker).',
  },
  {
    code: '62',
    system: 'BSAB 96',
    title: 'Högspänningssystem (> 1 kV)',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    scope: 'System för mellanspänning och högspänningsdistribution (normalt 10-24 kV).',
    typicalMaterials: ['Transformatorstation', 'Högspänningsställverk', 'Mellanspänningskablar AXCE/AXLJ'],
    iec81346Equivalents: ['=TA', '=QA', '-TA', '-QA'],
    iec61355Documents: ['&FS', '&FE', '&BD'],
    raNotes: 'Kräver behörighet och särskilda säkerhetsåtgärder enligt ESA (Elsäkerhetsanvisningarna).',
  },
  {
    code: '63',
    system: 'BSAB 96',
    title: 'Elkraftsystem och lågspänningsfördelning',
    category: 'Centraler, Ställverk & Skåp',
    scope: 'Lågspänningsdistribution (400/230 V) från nätägares anslutningspunkt till förbrukare.',
    typicalMaterials: ['Huvudställverk', 'Gruppcentraler', 'Stigarkablar', 'Säkringar', 'Mätare'],
    iec81346Equivalents: ['=W', '-QA', '-FC', '-QB'],
    iec61355Documents: ['&FS', '&FE', '&FA'],
    raNotes: 'Krav på selektivitet mellan skyddsapparater och beräkning av kortslutningsströmmar (Ik1, Ik3).',
  },
  {
    code: '63.1',
    system: 'BSAB 96',
    title: 'Huvudledningssystem och ställverk',
    category: 'Centraler, Ställverk & Skåp',
    parentCode: '63',
    scope: 'Inkommande servis, huvudställverk, mätarskåp, stigarskenor och huvudfördelningar.',
    typicalMaterials: ['Huvudställverk i moduler', 'Luftbrytare ACB', 'Effektbrytare MCCB', 'Kanaliserade strömskenor'],
    iec81346Equivalents: ['-QA', '-QF', '+W1'],
    iec61355Documents: ['&FS', '&FE', '&FA', '&FL'],
    raNotes: 'Utförs i formavskiljning (t.ex. Form 2b/4b) beroende på anläggningens krav och driftkontinuitet.',
  },
  {
    code: '63.2',
    system: 'BSAB 96',
    title: 'Gruppledningssystem och fördelningar',
    category: 'Centraler, Ställverk & Skåp',
    parentCode: '63',
    scope: 'Gruppcentraler (normkapslingar), gruppledningar, automatsäkringar och personskydd.',
    typicalMaterials: ['Normcentraler', 'Dvärgbrytare MCB', 'Jordfelsbrytare RCD (30 mA)', 'Installationskablar EXQ/EKK'],
    iec81346Equivalents: ['-FC', '-QA', '-F'],
    iec61355Documents: ['&FS', '&FE'],
    raNotes: 'Varje ny gruppledning ska skyddas av jordfelsbrytare enligt SS 436 40 00.',
  },
  {
    code: '63.3',
    system: 'BSAB 96',
    title: 'Reservkraftsystem',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    parentCode: '63',
    scope: 'Diesel- eller gasdrivna reservelverk med automatisk start och nätomkoppling vid strömavbrott.',
    typicalMaterials: ['Dieselaggregat', 'Automatisk reservkraftsomkopplare (ATS)', 'Drivmedelstank', 'Avgassystem'],
    iec81346Equivalents: ['-GA', '-QA'],
    iec61355Documents: ['&FS', '&WD'],
    raNotes: 'Periodisk provkörning med last och provningsprotokoll krävs enligt MSB och myndighetskrav.',
  },
  {
    code: '63.4',
    system: 'BSAB 96',
    title: 'Avbrottsfri kraft (UPS-system)',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    parentCode: '63',
    scope: 'Statiska UPS-anläggningar för servrar, sjukhusmiljöer och kritiska automationssystem.',
    typicalMaterials: ['UPS-aggregat (Online dubbelkonvertering)', 'VRLA/Litiumjon-batterier', 'Manuell förbikopplare (bypass)'],
    iec81346Equivalents: ['-TA', '-BT', '-G'],
    iec61355Documents: ['&FS', '&WD'],
    raNotes: 'Dimensioneras för erforderlig autonomitid (t.ex. 10, 30 eller 60 minuter) vid full last.',
  },
  {
    code: '63.5',
    system: 'BSAB 96',
    title: 'Lokal elproduktion och solcellsanläggningar',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    parentCode: '63',
    scope: 'Tak- eller markmonterade solceller, batterilager (BESS) och elfordonsladdning.',
    typicalMaterials: ['PV-paneler', 'Strängväxelriktare', 'DC-brytare', 'Överspänningsskydd Typ 1/2', 'Batterilager'],
    iec81346Equivalents: ['-PV', '-TA', '-QA'],
    iec61355Documents: ['&FS', '&PL', '&FA'],
    raNotes: 'Brandförsvarets räddningsbrytare och tydlig varningsmärkning för solcellsspänning är obligatorisk.',
  },
  {
    code: '63.6',
    system: 'BSAB 96',
    title: 'Elvärmesystem och värmekablar',
    category: 'Installationsapparater & Uttag',
    parentCode: '63',
    scope: 'Elektrisk golvvärme, frostskydd för VA-rör, hängrännor, stuprör och markuppvärmning.',
    typicalMaterials: ['Värmekabel självbegränsande', 'Golvvärmetermostat med golvgivare', 'Snö/is-styrning'],
    iec81346Equivalents: ['-EH', '-RN'],
    iec61355Documents: ['&FS', '&FL'],
    raNotes: 'Isolationsmätning och resistansmätning ska utföras före, under och efter ingjutning/förläggning.',
  },
  {
    code: '63.7',
    system: 'BSAB 96',
    title: 'Belysningssystem och ljusstyrning',
    category: 'Belysning & Belysningsstyrning',
    parentCode: '63',
    scope: 'Allmänbelysning, accentbelysning, dekorationsbelysning, fasadbelysning och DALI-styrning.',
    typicalMaterials: ['LED-paneler', 'Downlights', 'Linjär armatur', 'DALI-2 gateways', 'Närvarosensorer'],
    iec81346Equivalents: ['-EL', '-SF', '-KF'],
    iec61355Documents: ['&FS', '&FN', '&FA'],
    raNotes: 'Krav på bländtal (UGR < 19 för kontor) och färgåtergivning (Ra/CRI > 80/90) enligt SS-EN 12464-1.',
  },
  {
    code: '63.8',
    system: 'BSAB 96',
    title: 'Nödbelysningssystem och utrymningsskyltar',
    category: 'Belysning & Belysningsstyrning',
    parentCode: '63',
    scope: 'Belysta och genomlysta hänvisningsarmaturer samt panikbelysning längs utrymningsvägar.',
    typicalMaterials: ['Hänvisningsarmatur med piktogram', 'Decentraliserade batteriarmaturer', 'Centralt nödljusbatteri'],
    iec81346Equivalents: ['-EL', '-BT'],
    iec61355Documents: ['&FS', '&FN', '&FA'],
    raNotes: 'Drifttid minst 60 minuter vid strömbortfall enligt BBR och SS-EN 1838. Autotestfunktion rekommenderas.',
  },
  {
    code: '63.9',
    system: 'BSAB 96',
    title: 'Installationsapparater och eluttag',
    category: 'Installationsapparater & Uttag',
    parentCode: '63',
    scope: 'Vägguttag, strömbrytare, arbetsbrytare, industridon och anslutning av apparater.',
    typicalMaterials: ['2-vägsuttag jordat', 'Strömställare', 'CEE 400V 16/32A uttag', 'Säkerhetsbrytare'],
    iec81346Equivalents: ['-XB', '-SA', '-QM'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Säkerhetsbrytare ska monteras inom synhåll från maskin eller fläktmotor enligt SS-EN 60204-1.',
  },
  {
    code: '64',
    system: 'BSAB 96',
    title: 'Telesystem och informationsöverföring',
    category: 'Tele, Data & Fastighetsnät',
    scope: 'Infrastruktur för telekommunikation, datanätverk, TV, audio/video och tidvisning.',
    typicalMaterials: ['Patchpaneler', '19" rackskåp', 'Cat6A RJ45', 'Fiberoptik', 'Korskopplingar'],
    iec81346Equivalents: ['=E', '-XB', '-KF'],
    iec61355Documents: ['&FS', '&FN', '&FL'],
    raNotes: 'Följer svensk standard SS-EN 50173 och SS-EN 50174 för strukturerade fastighetsnät.',
  },
  {
    code: '64.1',
    system: 'BSAB 96',
    title: 'Fastighetsnät och strukturerade kabelsystem (LAN)',
    category: 'Tele, Data & Fastighetsnät',
    parentCode: '64',
    scope: 'Kopparkablage (Cat6A / Klass EA), fiberkablage, patchpaneler och RJ45-arbetsplatsuttag.',
    typicalMaterials: ['Cat 6A U/UTP eller F/UTP', 'Patchpaneler 24-port', 'Singelmode OS2 fiber', '19-tums rack'],
    iec81346Equivalents: ['-XB', '-W'],
    iec61355Documents: ['&FN', '&FL', '&FS'],
    raNotes: 'Varje länk ska certifieringsmätas med godkänd nätverkstestare (Fluke m.fl.) med protokoll i relationshandling.',
  },
  {
    code: '64.2',
    system: 'BSAB 96',
    title: 'Trådlösa nätverk och WiFi-infrastruktur',
    category: 'Tele, Data & Fastighetsnät',
    parentCode: '64',
    scope: 'Kablage, montageplatser och PoE+-matning för trådlösa accesspunkter och mobil inomhustäckning.',
    typicalMaterials: ['WiFi-6/7 accesspunkter', 'PoE+ nätverksswitchar', 'DAS antenner för mobil'],
    iec81346Equivalents: ['-WA', '-RN'],
    iec61355Documents: ['&FN'],
    raNotes: 'Placering ska utgå från radiomätning (site survey) för optimal täckning.',
  },
  {
    code: '64.5',
    system: 'BSAB 96',
    title: 'Ljud- och bildsystem (AV)',
    category: 'Tele, Data & Fastighetsnät',
    parentCode: '64',
    scope: 'Konferensrumsteknik, projektorer, interaktiva skärmar, hörselslingor och bakgrundsmusik.',
    typicalMaterials: ['Hörselslingeförstärkare', 'Takhögtalare 100V', 'HDMI/USB-C väggbrunnar', 'DSP-ljudprocessor'],
    iec81346Equivalents: ['-AA', '-BA'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Hörselslinga ska uppfylla SS-EN 60118-4 vad gäller fältstyrka och frekvensgång.',
  },
  {
    code: '65',
    system: 'BSAB 96',
    title: 'Säkerhetssystem',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    scope: 'Brandlarm, inbrottslarm, passersystem, kameraövervakning och utrymningssystem.',
    typicalMaterials: ['Centralapparater', 'Detektorer', 'Kortläsare', 'IP-kameror', 'Ellås'],
    iec81346Equivalents: ['=S', '-SF', '-KF', '-XB'],
    iec61355Documents: ['&FS', '&FN', '&FL'],
    raNotes: 'Strikt reglerat av SBF (Stöldskyddsföreningen / Brandskyddsföreningen) och försäkringskrav.',
  },
  {
    code: '65.1',
    system: 'BSAB 96',
    title: 'Brandlarmanläggningar',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    parentCode: '65',
    scope: 'Automatisk brandlarmscentral, adresserbara slingor, rökdetektorer, larmtryckknappar och siréner.',
    typicalMaterials: ['Optiska rökdetektorer', 'Larmknappar MCP', 'Blixtljus och siréner', 'Brandlarmskabel halogenfri'],
    iec81346Equivalents: ['-SF', '-WA', '-KF'],
    iec61355Documents: ['&FS', '&FN', '&FL', '&FA'],
    raNotes: 'Utförs enligt SBF 110:8. Kräver certifierad anläggarfirma och certifierad behörig ingenjör.',
  },
  {
    code: '65.2',
    system: 'BSAB 96',
    title: 'Utrymningslarm med talat meddelande (talat larm)',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    parentCode: '65',
    scope: 'Högtalaranläggning för evakuering av personal och besökare med automatiserade röstmeddelanden.',
    typicalMaterials: ['Certifierade EN 54-24 högtalare', 'Tal-larmcentral', 'Brandklassad kabel med funktionsbehållning E30/E90'],
    iec81346Equivalents: ['-AA', '-WA'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Utförs enligt SBF 502. Krav på taluppfattbarhet (STI-värde > 0,5) i alla utrymningszoner.',
  },
  {
    code: '65.3',
    system: 'BSAB 96',
    title: 'Inbrotts- och överfallslarmanläggningar',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    parentCode: '65',
    scope: 'Skalskydd och invändigt volymskydd för att upptäcka och larma vid obehörigt intrång.',
    typicalMaterials: ['Magnetkontakter på dörrar/fönster', 'Dualdetektorer PIR/MW', 'Glaskrossdetektorer', 'Larmknappar'],
    iec81346Equivalents: ['-SF', '-KF'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Projekteras enligt SSF 130 i larmklass 1, 2, 3 eller 4 beroende på verksamhet och stöldbegärlighet.',
  },
  {
    code: '65.4',
    system: 'BSAB 96',
    title: 'Passerkontrollsystem (Passersystem)',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    parentCode: '65',
    scope: 'Elektronisk låsning och tillträdeskontroll med beröringsfria RFID/Mifare-läsare.',
    typicalMaterials: ['Kortläsare', 'Dörrkontrollenheter (DAC)', 'Motorlås / Solenoidlås', 'Nödöppningsknappar gröna'],
    iec81346Equivalents: ['-SF', '-MB', '-KF'],
    iec61355Documents: ['&FS', '&FN', '&FL'],
    raNotes: 'Nödutrymning (gröna tryckknappar/nödvred) ska alltid bryta låsspänningen direkt oberoende av elektronik.',
  },
  {
    code: '65.5',
    system: 'BSAB 96',
    title: 'Kameraövervakningssystem (CCTV)',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    parentCode: '65',
    scope: 'Nätverksbaserad kameraövervakning, videoinspelning och övervakningscentraler.',
    typicalMaterials: ['IP-domekameror 4K/PoE', 'Nätverksvideobandspelare (NVR)', 'Kameramaster utomhus'],
    iec81346Equivalents: ['-BG', '-KF'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Kameraövervakningslagen och GDPR ställer krav på skyltning och lagringstid för bildmaterial.',
  },
  {
    code: '66',
    system: 'BSAB 96',
    title: 'Transportsystem (Hissar m.m.)',
    category: 'Transportsystem (Hissar m.m.)',
    scope: 'Vertikala och horisontella persontransporter inom byggnad.',
    typicalMaterials: ['Personhissar', 'Godshissar', 'Rulltrappor', 'Rullramper'],
    iec81346Equivalents: ['-MA', '-QA'],
    iec61355Documents: ['&FS', '&FA'],
    raNotes: 'Kräver hisskraftmatning, larmtelefon och brandstyrning (hissen ska gå till utrymningsplan vid brandlarm).',
  },
  {
    code: '67',
    system: 'BSAB 96',
    title: 'Styr- och övervakningssystem / Fastighetsautomation',
    category: 'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
    scope: 'System för reglering, mätning, styrning och optimering av värme, ventilation, kyla och belysning.',
    typicalMaterials: ['DUC/DDC-centraler', 'Fältbussar Modbus/BACnet', 'Givare', 'Ställdon', 'SCADA-server'],
    iec81346Equivalents: ['=K', '-KF', '-BP', '-BT', '-QM'],
    iec61355Documents: ['&FS', '&FN', '&WD', '&FL'],
    raNotes: 'Kärnan i moderna energieffektiva fastigheter. Gränsdragning mot el- och VS-entreprenader ska preciseras noga.',
  },
  {
    code: '67.1',
    system: 'BSAB 96',
    title: 'Överordnat system (SCADA / BMS)',
    category: 'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
    parentCode: '67',
    scope: 'Central servermiljö med grafiska flödesbilder, larmpresentation, trendloggning och energianalys.',
    typicalMaterials: ['BMS-mjukvara', 'Serverdator', 'Klientdatorer', 'Brandväggar för OT-nätverk'],
    iec81346Equivalents: ['-KF', '-WD'],
    iec61355Documents: ['&WD', '&FS'],
    raNotes: 'Kräver robust IT/OT-säkerhet med isolerade VLAN och krypterad fjärråtkomst (VPN).',
  },
  {
    code: '67.2',
    system: 'BSAB 96',
    title: 'Undercentraler och styrskåp (DUC / DDC)',
    category: 'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
    parentCode: '67',
    scope: 'Programmerbara styrenheter (DUC) i apparatskåp för fläktrum, undercentraler och kylanläggningar.',
    typicalMaterials: ['DUC-kontrollers', 'I/O-expansionsmoduler', '24V DC nätaggregat', 'Plintrad med frånskiljarklämmor'],
    iec81346Equivalents: ['-KF', '+W_DUC', '-XB'],
    iec61355Documents: ['&FS', '&FE', '&FA', '&FL'],
    raNotes: 'Skåplayout ska möjliggöra god ventilation och tydlig separation mellan starkström (230V) och SELV (24V).',
  },
  {
    code: '67.4',
    system: 'BSAB 96',
    title: 'Fältbussystem och nätverk',
    category: 'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
    parentCode: '67',
    scope: 'Kommunikationsbussar mellan regulatorer, givare, ventilställdon och elmätare.',
    typicalMaterials: ['BACnet MS/TP och IP', 'Modbus RTU RS485', 'M-Bus för energimätare', 'KNX för rumsautomation'],
    iec81346Equivalents: ['-W', '-KF'],
    iec61355Documents: ['&WD', '&FS'],
    raNotes: 'Korrekt terminering (ändmotstånd 120 ohm på RS485) och partvinnad skärmad kabel är kritiskt.',
  },
  {
    code: '68',
    system: 'BSAB 96',
    title: 'Jordningssystem, åskskydd och spänningsutjämning',
    category: 'Jordning, Åskskydd & Potentialutjämning',
    scope: 'Skyddsjordning, potentialutjämning (PUS), åskskyddsanläggningar och transientavledare.',
    typicalMaterials: ['Huvudjordningsskena HJS', 'Kopparlina 50 mm²', 'Jordspett', 'Överspänningsskydd'],
    iec81346Equivalents: ['-PE', '-ET', '-FB'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Dimensioneras enligt SS 436 40 00 och SS-EN 62305 för att eliminera beröringsspänningar.',
  },

  // ==========================================
  // AMA EL - KAPITEL E (ELTEKNISKA ANLÄGGNINGAR)
  // ==========================================
  {
    code: 'EB',
    system: 'AMA EL',
    title: 'Kanalisation och förläggning av kablar',
    category: 'Kanalisation & Förläggning',
    scope: 'Övergripande krav på material, montering, bärförmåga och brandtätning för kabelförläggning.',
    typicalMaterials: ['Kabelstegar', 'Kabelrännor', 'Rör', 'Brandtätningsmassa', 'Konsoler'],
    iec81346Equivalents: ['+W'],
    iec61355Documents: ['&FN', '&FL'],
    raNotes: 'Brandtätning ska utföras i samma brandklass som genombruten byggnadsdel (EI60, EI90 etc.).',
  },
  {
    code: 'EBB',
    system: 'AMA EL',
    title: 'Förläggningsmaterial för kablar i mark',
    category: 'Kanalisation & Förläggning',
    parentCode: 'EB',
    scope: 'Skyddsrör, kabelskydd, kabelbrunnar och varningsband vid markförläggning.',
    typicalMaterials: ['Kabelskyddsrör SRN (normal) och SRS (svår)', 'Gult plastband med text KABEL', 'Täckskydd av plast/stål'],
    iec81346Equivalents: ['+G'],
    iec61355Documents: ['&FN', '&PL'],
    raNotes: 'I gatumark och under hårdgjord yta ska rör i klass SRS väljas.',
  },
  {
    code: 'EBC',
    system: 'AMA EL',
    title: 'Kabelstegar och kabelrännor',
    category: 'Kanalisation & Förläggning',
    parentCode: 'EB',
    scope: 'Öppna och perforerade bärsystem i plåt, tråd eller syrafast material för kablage.',
    typicalMaterials: ['Kabelstegar MP / Wibe', 'Trådstegar Defem', 'Armaturskenor', 'Pendlingsstänger M10'],
    iec81346Equivalents: ['+W'],
    iec61355Documents: ['&FN'],
    raNotes: 'Kabelstegar ska jordas/potentialutjämnas om de löper genom explosionsfarliga rum eller utomhus.',
  },
  {
    code: 'EBD',
    system: 'AMA EL',
    title: 'Elinstallationskanaler',
    category: 'Kanalisation & Förläggning',
    parentCode: 'EB',
    scope: 'Väggkanaler, fönsterbänkskanaler, golvkanaler och kabellister med frontöppning.',
    typicalMaterials: ['Aluminiumkanal 120/170 mm', 'Plastkanal halogenfri', 'Hörn- och ändstycken', 'Uttagslådor'],
    iec81346Equivalents: ['+W', '+R'],
    iec61355Documents: ['&FN'],
    raNotes: 'Frontlock ska sitta fast stadigt men kunna demonteras vid framtida kabeldragning.',
  },
  {
    code: 'EBE',
    system: 'AMA EL',
    title: 'Installationsrör och böjliga rör',
    category: 'Kanalisation & Förläggning',
    parentCode: 'EB',
    scope: 'Plaströr och böjliga korrugerade slangar (flexrör) för infälld förläggning i vägg och valv.',
    typicalMaterials: ['VP-rör 16/20/25 mm', 'Flexslang med fördragen ledare (FK/FQ)', 'Skarvmuffar med spärrfjäder'],
    iec81346Equivalents: ['+W'],
    iec61355Documents: ['&FN'],
    raNotes: 'Flexrör ska klamras med max 0,6 m avstånd och fästas noga före betonggjutning.',
  },
  {
    code: 'EC',
    system: 'AMA EL',
    title: 'Kablar och ledningar',
    category: 'Kablar & Ledningar',
    scope: 'Generella krav på ledare, isolering, CPR-brandklasser och mantlar för el- och telekablar.',
    typicalMaterials: ['Halogenfria kablar (HFFR)', 'Kopparledare', 'Skärmade signalkablar', 'Optiska kablar'],
    iec81346Equivalents: ['-W'],
    iec61355Documents: ['&FL', '&FS'],
    raNotes: 'Enligt BBR och SS-EN 50575 ställs krav på CPR-klass Dca-s2,d2 eller Cca-s1,d1 i publika byggnader.',
  },
  {
    code: 'ECC',
    system: 'AMA EL',
    title: 'Kraftkablar och belysningskablar',
    category: 'Kablar & Ledningar',
    parentCode: 'EC',
    scope: 'Starkströmskablar för 230/400 V fast installation i rör, på stege eller öppet på vägg.',
    typicalMaterials: ['EXQ Easy (vit installationskabel)', 'FXQ (kraftkabel halogenfri)', 'N1XV (markkabel koppar)', 'AXQJ (aluminium)'],
    iec81346Equivalents: ['-W', '-W1'],
    iec61355Documents: ['&FL', '&FS'],
    raNotes: 'Halogenfria kablar ska väljas för att undvika giftig och frätande saltsyra vid brand.',
  },
  {
    code: 'ECD',
    system: 'AMA EL',
    title: 'Signalkablar och styrkablar',
    category: 'Kablar & Ledningar',
    parentCode: 'EC',
    scope: 'Flerledarkablar för manöver-, larm- och analoga mätsignaler i styr- och automationsanläggningar.',
    typicalMaterials: ['LiYCY (skärmad styrkabel)', 'EKKX (tele-/larmkabel)', 'Ölflex Classic', 'Partvinnade signallingar'],
    iec81346Equivalents: ['-W'],
    iec61355Documents: ['&FL', '&FS'],
    raNotes: 'Skärm ska normalt jordas i en ände (vid apparatskåp) för att förhindra jordslingor vid lågfrekvent störning.',
  },
  {
    code: 'ECE',
    system: 'AMA EL',
    title: 'Tele- och datakablar',
    category: 'Kablar & Ledningar',
    parentCode: 'EC',
    scope: 'Partvinnade kablar för strukturerade fastighetsnät upp till 10 Gbit/s.',
    typicalMaterials: ['Cat 6A U/FTP eller S/FTP', 'Cat 6 U/UTP', 'Halogenfri yttermantel LSZH'],
    iec81346Equivalents: ['-W'],
    iec61355Documents: ['&FL', '&FN'],
    raNotes: 'Max tillåten länkavstånd är 90 meter fast installation + 10 meter patchkablar (totalt 100 m).',
  },
  {
    code: 'ECF',
    system: 'AMA EL',
    title: 'Optiska kablar (Fiberkabel)',
    category: 'Kablar & Ledningar',
    parentCode: 'EC',
    scope: 'Fiberoptiska kablar för stamnät mellan datahallar, fastigheter och våningskorskopplingar.',
    typicalMaterials: ['Singelmode 9/125 µm (OS2)', 'Multimod 50/125 µm (OM4)', 'Loose-tube fiber med gnagarskydd'],
    iec81346Equivalents: ['-W'],
    iec61355Documents: ['&FL', '&FN'],
    raNotes: 'Dämpningsmätning (OTDR och dämpningsbudget) ska bifogas vid godkännande.',
  },
  {
    code: 'ECG',
    system: 'AMA EL',
    title: 'Brandresistenta kablar och funktionssäkra ledningar',
    category: 'Kablar & Ledningar',
    parentCode: 'EC',
    scope: 'Kablar med funktionsbehållning vid brand (t.ex. 30, 60 eller 90 minuter) för utrymnings- och säkerhetssystem.',
    typicalMaterials: ['Brandresistent kabel FE180 / E30-E90', 'Silikonisolering med glimmerband', 'Orange mantel'],
    iec81346Equivalents: ['-W'],
    iec61355Documents: ['&FL', '&FS'],
    raNotes: 'Kräver godkända bärverk och klamrar som klarar brandpåverkan utan att rasa ned.',
  },
  {
    code: 'ED',
    system: 'AMA EL',
    title: 'Elkopplingsanläggningar, ställverk och centraler',
    category: 'Centraler, Ställverk & Skåp',
    scope: 'Övergripande krav på tillverkning, typprovning (SS-EN 61439), kapslingsklasser och beröringsskydd.',
    typicalMaterials: ['Plåtkapslingar', 'Samlingsskenor', 'Beröringsskydd IP20/IP30', 'Huvudströmbrytare'],
    iec81346Equivalents: ['+W', '-QA'],
    iec61355Documents: ['&FE', '&FS', '&FA'],
    raNotes: 'Verifikation och typprovningsunderlag enligt SS-EN 61439-1 och -2 ska överlämnas.',
  },
  {
    code: 'EDB',
    system: 'AMA EL',
    title: 'Högspänningsställverk',
    category: 'Centraler, Ställverk & Skåp',
    parentCode: 'ED',
    scope: 'Mellanspänningsställverk för 12-24 kV med SF6-gas eller vakuumkretsbrytare.',
    typicalMaterials: ['Vakuumströmbrytare', 'Lastfrånskiljare', 'Jordningskopplare', 'Skyddsreläer SIPROTEC'],
    iec81346Equivalents: ['-QA', '-QB', '-KF'],
    iec61355Documents: ['&FS', '&FE', '&BD'],
    raNotes: 'Mekanisk och elektrisk förregling mot felmanöver (t.ex. att slå till jord med spänning på).',
  },
  {
    code: 'EDC',
    system: 'AMA EL',
    title: 'Lågspänningsställverk',
    category: 'Centraler, Ställverk & Skåp',
    parentCode: 'ED',
    scope: 'Huvudställverk för strömmar från 630 A upp till flera tusen ampere.',
    typicalMaterials: ['Luftbrytare ACB', 'Kompakta effektbrytare MCCB', 'Kopparskenor', 'Kabelanslutningsfält'],
    iec81346Equivalents: ['-QA', '-QF'],
    iec61355Documents: ['&FS', '&FE', '&FA'],
    raNotes: 'Termografering ska kunna utföras vid drift. Skyddsklass normalt IP31 eller IP54.',
  },
  {
    code: 'EDD',
    system: 'AMA EL',
    title: 'Centraler och fördelningsskåp (Gruppcentraler)',
    category: 'Centraler, Ställverk & Skåp',
    parentCode: 'ED',
    scope: 'Normcentraler i plåt eller plast för bostäder, kontor och industrier.',
    typicalMaterials: ['Normslitsar på DIN-skena', 'Fasskenor', 'Noll- och PE-skenor', 'Kapsling IP30/IP41/IP65'],
    iec81346Equivalents: ['+W', '-QA', '-FC'],
    iec61355Documents: ['&FS', '&FE'],
    raNotes: 'Minst 20-30 % reservplats på DIN-skenorna för framtida utökning.',
  },
  {
    code: 'EDE',
    system: 'AMA EL',
    title: 'Apparatskåp och styrskåp',
    category: 'Centraler, Ställverk & Skåp',
    parentCode: 'ED',
    scope: 'Kapslingar för automationsutrustning, DUC, PLC, reläer och motorstyrningar.',
    typicalMaterials: ['Golv- och väggskåp Rittal', 'Montageplåt', 'Kabelkanaler med slitsad kam', 'Fläkt/filter'],
    iec81346Equivalents: ['+W', '-KF'],
    iec61355Documents: ['&FE', '&FS', '&FA'],
    raNotes: 'Följer SS-EN 60204-1 (Maskiners elutrustning) med huvudbrytare, nödstopp och 24V manöverspänning.',
  },
  {
    code: 'EDF',
    system: 'AMA EL',
    title: 'Komponenter i elkopplingsanläggningar',
    category: 'Centraler, Ställverk & Skåp',
    parentCode: 'ED',
    scope: 'Dvärgbrytare, effektbrytare, jordfelsbrytare, kontaktorer, tidur och övervakningsreläer.',
    typicalMaterials: ['Dvärgbrytare 10A/16A B/C-karaktäristik', 'Jordfelsbrytare 30mA Typ A', 'Kontaktorer', 'Plintar'],
    iec81346Equivalents: ['-FC', '-QA', '-KM', '-XB'],
    iec61355Documents: ['&FS', '&FA'],
    raNotes: 'Brytförmåga ska anpassas till dimensionerande kortslutningsström (t.ex. 6 kA eller 10 kA).',
  },
  {
    code: 'EE',
    system: 'AMA EL',
    title: 'Kraftförsörjningssystem och reservkraft',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    scope: 'Transformatorer, generatorer, UPS-aggregat, likriktare och solcellsinstallationer.',
    typicalMaterials: ['Torrtransformatorer', 'UPS', 'Dieselgenerator', 'PV-växelriktare'],
    iec81346Equivalents: ['-TA', '-GA', '-BT'],
    iec61355Documents: ['&FS', '&WD'],
    raNotes: 'Driftsäkerhet och sammankoppling med elnätet kräver godkännande från nätägaren.',
  },
  {
    code: 'EEB',
    system: 'AMA EL',
    title: 'Transformatorer',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    parentCode: 'EE',
    scope: 'Distributionstransformatorer (t.ex. 20/0,4 kV) och manövertransformatorer för 24/230V.',
    typicalMaterials: ['Gjuthartstransformator', 'Oljetransformator med oljeuppsamlingsgrop', 'PT100-termostater'],
    iec81346Equivalents: ['-TA'],
    iec61355Documents: ['&FS', '&BD'],
    raNotes: 'Temperaturövervakning och larm vid övertemperatur ska kopplas till fastighetsautomation eller SCADA.',
  },
  {
    code: 'EEC',
    system: 'AMA EL',
    title: 'Reservkraftaggregat',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    parentCode: 'EE',
    scope: 'Dieseldrivna elverk för kontinuerlig eller tillfällig kraftförsörjning vid spänningsbortfall.',
    typicalMaterials: ['Dieselmotor med generator', 'Startbatterier med laddare', 'Ljuddämpande huv', 'ATS omkopplare'],
    iec81346Equivalents: ['-GA', '-QA'],
    iec61355Documents: ['&FS', '&WD'],
    raNotes: 'Automatisk fasning eller brytning före slutning (make-before-break / break-before-make) ska verifieras.',
  },
  {
    code: 'EED',
    system: 'AMA EL',
    title: 'Avbrottsfri kraftförsörjning (UPS)',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    parentCode: 'EE',
    scope: 'Statiska växelriktare med batteribackup för transientfri och kontinuerlig kraft.',
    typicalMaterials: ['UPS-rack', 'Underhållsfria blybatterier VRLA', 'Litiumjärnfosfat (LiFePO4)', 'Statisk bypassbrytare'],
    iec81346Equivalents: ['-TA', '-BT', '-G'],
    iec61355Documents: ['&FS', '&WD'],
    raNotes: 'Miljökrav i batterirum: God ventilation (för att evakuera vätgas vid blybatterier) och rätt temperatur (20 °C).',
  },
  {
    code: 'EEF',
    system: 'AMA EL',
    title: 'Solcellsanläggningar (Fotovoltaik)',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    parentCode: 'EE',
    scope: 'Solpaneler på tak/mark, växelriktare, DC-ledningar och säkerhetsbrytare för solel.',
    typicalMaterials: ['Monokristallina solcellspaneler', 'Strängväxelriktare', 'Solkabel H1Z2Z2-K', 'MC4-kontakter'],
    iec81346Equivalents: ['-PV', '-TA', '-QA'],
    iec61355Documents: ['&FS', '&PL', '&FA'],
    raNotes: 'DC-brytare ska vara godkänd för likström och monteras nära växelriktaren. Varning för DC-spänning upp till 1000V.',
  },
  {
    code: 'EEG',
    system: 'AMA EL',
    title: 'Batterilagringssystem för fastighet (BESS)',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    parentCode: 'EE',
    scope: 'Stationära batterisystem för lagring av solenergi, effekttoppkapning och stödtjänster.',
    typicalMaterials: ['Litiumjonbatterimoduler', 'BMS (Battery Management System)', 'Hybridväxelriktare'],
    iec81346Equivalents: ['-BT', '-TA'],
    iec61355Documents: ['&FS', '&WD'],
    raNotes: 'Brandskyddsföreningens riktlinjer för stationära energilager ska följas avseende brandcell och släckgas.',
  },
  {
    code: 'EEH',
    system: 'AMA EL',
    title: 'Laddstationer för fordon (Elbilsladdning)',
    category: 'Kraftförsörjning, Reservkraft & Solceller',
    parentCode: 'EE',
    scope: 'Laddboxar Typ 2 AC och snabbladdare DC för elbilar med lastbalansering och betalsystem.',
    typicalMaterials: ['Laddbox 11/22 kW Typ 2', 'Dynamisk lastbalanserare', 'Energimätare MID-godkänd', 'RFID-läsare'],
    iec81346Equivalents: ['-XB', '-QA', '-KF'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Varje laddpunkt ska skyddas av egen jordfelsbrytare Typ A med DC-skydd (6 mA DC) eller Typ B.',
  },
  {
    code: 'EK',
    system: 'AMA EL',
    title: 'Installationsapparater och uttag',
    category: 'Installationsapparater & Uttag',
    scope: 'Mekaniska och elektroniska apparater för infällt och utanpåliggande montage.',
    typicalMaterials: ['Strömställare', 'Vägguttag', 'Dimmers', 'Kopplingsdosor', 'CEE-don'],
    iec81346Equivalents: ['-SA', '-XB', '-RN'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Monteras på standardhöjder: strömställare 1000 mm ög, vägguttag 200 mm ög (arbetsbänk 1100 mm).',
  },
  {
    code: 'EKB',
    system: 'AMA EL',
    title: 'Strömställare och tryckknappar',
    category: 'Installationsapparater & Uttag',
    parentCode: 'EK',
    scope: 'Vippströmställare, tryckknappar, nyckelbrytare och jalusibrytare.',
    typicalMaterials: ['1-polig, trapp, kors och kron', 'Fjädrande vippor med impulsfjäder', 'Ramverk i termoplast'],
    iec81346Equivalents: ['-SA'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Trappkoppling eller impulsstyrning (relä) används vid flera manövreringspunkter för samma belysningsgrupp.',
  },
  {
    code: 'EKC',
    system: 'AMA EL',
    title: 'Dimmers, tidsbrytare och sensorer',
    category: 'Installationsapparater & Uttag',
    parentCode: 'EK',
    scope: 'Elektroniska ljusregleringsdon, timer och närvarovakter för infällt dosmontage.',
    typicalMaterials: ['Fasdimmer bakkant (RC)', 'DALI-potentiometer', 'Närvarodetektor 360° PIR', 'Kopplingsur'],
    iec81346Equivalents: ['-RN', '-SF', '-KF'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Vid LED-laster är det viktigt att dimmern är certifierad för bakkantsstyrning (trailing edge) och LED.',
  },
  {
    code: 'EKD',
    system: 'AMA EL',
    title: 'Vägguttag för allmänbruk',
    category: 'Installationsapparater & Uttag',
    parentCode: 'EK',
    scope: '1-vägs, 2-vägs och 4-vägs jordade uttag 230 V 16 A för bostäder och kommersiella lokaler.',
    typicalMaterials: ['2-vägsuttag jordat petskyddat', 'Euro-uttag', 'Kapslade uttag IP44 med fällock'],
    iec81346Equivalents: ['-XB'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Alla uttag upp till 32 A för allmänt bruk ska föregås av jordfelsbrytare med märkutlösningsström max 30 mA.',
  },
  {
    code: 'EKE',
    system: 'AMA EL',
    title: 'Industridon och CEE-uttag',
    category: 'Installationsapparater & Uttag',
    parentCode: 'EK',
    scope: 'Kraftuttag för industri, verkstad och byggarbetsplatser enligt IEC 60309.',
    typicalMaterials: ['CEE-uttag 400V 16A/32A/63A 5-pol', 'Kombinationsuttag med dvärgbrytare', 'Sköljtäta don IP67'],
    iec81346Equivalents: ['-XB'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Monteras normalt med inbyggd personskyddsbrytare eller förreglad säkerhetsbrytare i industri.',
  },
  {
    code: 'EL',
    system: 'AMA EL',
    title: 'Belysningssystem och belysningsarmaturer',
    category: 'Belysning & Belysningsstyrning',
    scope: 'Armaturer, ljuskällor, driftdon och ljusstyrsystem för inom- och utomhusmiljöer.',
    typicalMaterials: ['LED-armaturer', 'DALI-drivdon', 'Optik/reflektorer', 'Stolpar och fästen'],
    iec81346Equivalents: ['-EL', '-KF'],
    iec61355Documents: ['&FS', '&FN', '&FA'],
    raNotes: 'Livslängd på LED ska specificeras som minst L80B10 > 50 000 eller 100 000 brinntimmar.',
  },
  {
    code: 'ELB',
    system: 'AMA EL',
    title: 'Allmänbelysningsarmaturer (Inomhus)',
    category: 'Belysning & Belysningsstyrning',
    parentCode: 'EL',
    scope: 'Tak- och väggarmaturer i kontor, skolor, sjukhus, industrilokaler och lager.',
    typicalMaterials: ['LED-plattor 600x600', 'Pendelarmaturer med direkt/indirekt ljus', 'Industrilinjär armatur IP65'],
    iec81346Equivalents: ['-EL'],
    iec61355Documents: ['&FS', '&FN', '&FA'],
    raNotes: 'Kontrollera flimmer (flicker free / Pst LM < 1,0) för god arbetsmiljö.',
  },
  {
    code: 'ELC',
    system: 'AMA EL',
    title: 'Utomhusbelysningsarmaturer',
    category: 'Belysning & Belysningsstyrning',
    parentCode: 'EL',
    scope: 'Fasadbelysning, stolparmaturer, pollare, markspotar och strålkastare.',
    typicalMaterials: ['Gatubelysningsarmaturer LED', 'Pollare IP65 IK10', 'Asymmetriska strålkastare för parkering'],
    iec81346Equivalents: ['-EL'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Korrosionsklass C4 eller C5 krävs vid kustområden eller utsatta miljöer.',
  },
  {
    code: 'ELD',
    system: 'AMA EL',
    title: 'Nödbelysningsarmaturer och hänvisningsskyltar',
    category: 'Belysning & Belysningsstyrning',
    parentCode: 'EL',
    scope: 'Genomlysta piktogram för utrymning och säkerhetsbelysning vid spänningsavbrott.',
    typicalMaterials: ['Gröna piktogram (springande gubbe / pil)', 'LED-nödljusspot med lins', 'Inbyggt LiFePO4-batteri'],
    iec81346Equivalents: ['-EL', '-BT'],
    iec61355Documents: ['&FS', '&FN', '&FA'],
    raNotes: 'Ska ge minst 1 lux på golvet längs utrymningsvägens centrumlinje enligt SS-EN 1838.',
  },
  {
    code: 'ELE',
    system: 'AMA EL',
    title: 'Belysningsstyrningssystem',
    category: 'Belysning & Belysningsstyrning',
    parentCode: 'EL',
    scope: 'DALI-2 styrsystem, trådlös styrning (Bluetooth Mesh/Casambi), skymningsrelä och astrour.',
    typicalMaterials: ['DALI-2 master/router', 'Multisensorer (närvaro + dagsljus)', 'Tryckknappsgränssnitt'],
    iec81346Equivalents: ['-KF', '-SF'],
    iec61355Documents: ['&FS', '&WD'],
    raNotes: 'DALI-bussen är polaritetsoberoende och kan förläggas i samma 5-ledarkabel (1,5 mm²) som kraften.',
  },
  {
    code: 'EP',
    system: 'AMA EL',
    title: 'Motorer, frekvensomriktare och drivsystem',
    category: 'Drivsystem, Motorer & Kraftuttag',
    scope: 'Elektriska motorer, mjukstartare, frekvensomriktare och maskinanslutningar.',
    typicalMaterials: ['Trefasmotorer', 'Frekvensomriktare VFD', 'Skärmad motorkabel', 'EMC-förskruvningar'],
    iec81346Equivalents: ['-MA', '-TA'],
    iec61355Documents: ['&FS', '&WC', '&FA'],
    raNotes: 'Motorkabel ska vara symmetrisk och skärmad med 360° EMC-jordning i båda ändar för att dämpa störningar.',
  },
  {
    code: 'EPC',
    system: 'AMA EL',
    title: 'Frekvensomriktare och mjukstartare',
    category: 'Drivsystem, Motorer & Kraftuttag',
    parentCode: 'EP',
    scope: 'Varvtalsreglering av pumpar, fläktar och transportbanor med fältbussanslutning.',
    typicalMaterials: ['Frekvensomriktare IP20/IP54', 'EMC-filter C2/C3', 'Bromsmotstånd', 'Safe Torque Off (STO)'],
    iec81346Equivalents: ['-TA', '-QM'],
    iec61355Documents: ['&FS', '&WC', '&FA'],
    raNotes: 'Parameterlista (&WC) ska sparas som dokumentation för snabb reservdelssättning vid haveri.',
  },
  {
    code: 'ET',
    system: 'AMA EL',
    title: 'Jordning, skydd och potentialutjämning',
    category: 'Jordning, Åskskydd & Potentialutjämning',
    scope: 'Huvudpotentialutjämning, kompletterande potentialutjämning, jordtag och skyddsledare.',
    typicalMaterials: ['Kopparskenor HJS', 'Gul/grön ledare MK/FK', 'Överspänningsskydd', 'Jordtagslinor'],
    iec81346Equivalents: ['-PE', '-FB'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Samtliga inkommande metallrör (vatten, gas, fjärrvärme) och byggnadsstål ska anslutas till HJS.',
  },
  {
    code: 'ETC',
    system: 'AMA EL',
    title: 'Skyddsledare och potentialutjämningsledare',
    category: 'Jordning, Åskskydd & Potentialutjämning',
    parentCode: 'ET',
    scope: 'PE-ledare, PEN-ledare, huvudpotentialutjämningsledare och kompletterande PUS i badrum/våtutrymmen.',
    typicalMaterials: ['Kopparlina 6/10/16/25/50 mm²', 'Presskabelskor', 'C-klämmor för armeringsjärn'],
    iec81346Equivalents: ['-PE'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Övergångsmotstånd mellan utsatt del och huvudjordningsskena ska kontrolleras vid idrifttagning.',
  },
  {
    code: 'ETD',
    system: 'AMA EL',
    title: 'Överspänningsskydd (Transientavledare)',
    category: 'Jordning, Åskskydd & Potentialutjämning',
    parentCode: 'ET',
    scope: 'Skydd mot blixtöverslag och nättransienter i elkopplingsanläggningar.',
    typicalMaterials: ['Typ 1 grovskydd (gnistgap 10/350 µs)', 'Typ 2 mellanskydd (varistor 8/20 µs)', 'Signallinjeskydd'],
    iec81346Equivalents: ['-FB', '-F'],
    iec61355Documents: ['&FS', '&FA'],
    raNotes: 'Anslutningsledarnas sammanlagda längd får max vara 0,5 meter för att minimera induktivt spänningsfall.',
  },
  {
    code: 'ETE',
    system: 'AMA EL',
    title: 'Åskskyddsanläggningar',
    category: 'Jordning, Åskskydd & Potentialutjämning',
    parentCode: 'ET',
    scope: 'Externt åskskydd med takledare, fångststänger, nedledare och kontrollmätställen.',
    typicalMaterials: ['Aluminiumtråd Ø 8 mm', 'Koppartråd Ø 8 mm', 'Fångststänger', 'Mät- och testklamrar'],
    iec81346Equivalents: ['-FB'],
    iec61355Documents: ['&FN', '&PL'],
    raNotes: 'Utförs enligt SS-EN 62305 klass I, II, III eller IV baserat på riskanalys.',
  },
  {
    code: 'EU',
    system: 'AMA EL',
    title: 'Teletekniska anläggningar och datanät',
    category: 'Tele, Data & Fastighetsnät',
    scope: 'Generella krav på datanät, rack, kabelhantering och telekommunikation.',
    typicalMaterials: ['19-tums rack', 'PDU grenuttag', 'Korskopplingspaneler', 'Keystone-moduler'],
    iec81346Equivalents: ['-XB', '-W'],
    iec61355Documents: ['&FN', '&FL', '&FS'],
    raNotes: 'God böjradie och dragavlastning ska säkerställas så att partvinnad kabel inte deformeras.',
  },
  {
    code: 'EUB',
    system: 'AMA EL',
    title: 'Fastighetsnät för data och tele (Strukturerat kablage)',
    category: 'Tele, Data & Fastighetsnät',
    parentCode: 'EU',
    scope: 'Koppar- och fiberbaserade fastighetsnät för kontor, skolor och flerbostadshus.',
    typicalMaterials: ['Cat 6A RJ45-jack', 'Dubbeluttag infällt/utanpå', 'Stamfiberkablar', 'Optiska korskopplingar (ODF)'],
    iec81346Equivalents: ['-XB', '-W'],
    iec61355Documents: ['&FN', '&FL'],
    raNotes: 'Permanent Link-test ska visa godkänt resultat för NEXT, return loss och delay skew.',
  },
  {
    code: 'EUC',
    system: 'AMA EL',
    title: 'Korskopplingsstativ och 19-tums rackskåp',
    category: 'Tele, Data & Fastighetsnät',
    parentCode: 'EU',
    scope: 'Golvstående och väggmonterade 19"-stativ för våningskorskopplingar och serverrum.',
    typicalMaterials: ['42U golvrack 800x1000 mm', 'Glasdörr med ventilation', 'Kabelledare och fingerskenor', 'Jordningsskena för rack'],
    iec81346Equivalents: ['+W', '-PE'],
    iec61355Documents: ['&FE', '&FN'],
    raNotes: 'Varje stativ ska jordas till telejord/huvudjord med minst 16 mm² kopparledare.',
  },
  {
    code: 'EV',
    system: 'AMA EL',
    title: 'Säkerhetssystem',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    scope: 'Krav på certifierade säkerhetsanläggningar, installation och provning.',
    typicalMaterials: ['Säkerhetskablar', 'Larmcentraler', 'Detektorer', 'Kortläsare'],
    iec81346Equivalents: ['=S', '-SF', '-KF'],
    iec61355Documents: ['&FS', '&FN', '&FL'],
    raNotes: 'Ingrepp i säkerhetsanläggningar ska utföras av godkänd anläggarfirma.',
  },
  {
    code: 'EVB',
    system: 'AMA EL',
    title: 'Brandlarmanläggningar',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    parentCode: 'EV',
    scope: 'Automatisk brandlarmscentral, slingkablage, rök- och värmedetektorer, larmdon och styrningar.',
    typicalMaterials: ['Optiska rökdetektorer adresserbara', 'Larmtryckknappar röda', 'Slingkort', 'Larmdon siréner och blixtljus'],
    iec81346Equivalents: ['-SF', '-WA', '-KF'],
    iec61355Documents: ['&FS', '&FN', '&FL', '&FA'],
    raNotes: 'Ska installeras enligt SBF 110. Styrningar mot branddörrstängning, ventilation och hiss ska provas årligen.',
  },
  {
    code: 'EVC',
    system: 'AMA EL',
    title: 'Utrymningslarm med talat meddelande (Tal-larm)',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    parentCode: 'EV',
    scope: 'Högtalarsystem och förstärkare certifierade enligt SS-EN 54 för utrymningsinstruktioner vid brand.',
    typicalMaterials: ['Tal-larmcentral EN 54-16', 'Takmonterade högtalare med keramisk plint', 'Batteribackup 24 timmar'],
    iec81346Equivalents: ['-AA', '-WA'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Kabel ska uppfylla brandfunktionskrav och förläggas på brandsäkra bärverk.',
  },
  {
    code: 'EVD',
    system: 'AMA EL',
    title: 'Inbrottslarmanläggningar',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    parentCode: 'EV',
    scope: 'Larmcentral, manöverpaneler, rörelsedetektorer, seismiska detektorer och larmöverföring.',
    typicalMaterials: ['Larmcentral godkänd SSF 1014', 'PIR/Mikrovågsdetektorer', 'Kassaskåpsdetektorer', 'Överföringsterminal 4G/IP'],
    iec81346Equivalents: ['-SF', '-KF'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Larmklass 1-3 bestämmer krav på sabotageövervakning, dubbelbalansering och backup-strömförsörjning.',
  },
  {
    code: 'EVE',
    system: 'AMA EL',
    title: 'Passerkontrollsystem (Passersystem)',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    parentCode: 'EV',
    scope: 'Dörrmiljöer med läsare, ellås, motorlås, öppnaknappar och integrering mot inbrottslarm.',
    typicalMaterials: ['Mifare DESFire EV2/EV3 läsare', 'Dörrkontrollenhet DAC', 'Motorlås med slutbleck', 'Spiralkabel'],
    iec81346Equivalents: ['-SF', '-MB', '-KF'],
    iec61355Documents: ['&FS', '&FN', '&FL'],
    raNotes: 'Brandutrymningskrav går före skalskyddskrav; ellås måste friställas eller ha mekaniskt vred.',
  },
  {
    code: 'EVF',
    system: 'AMA EL',
    title: 'Kameraövervakningssystem (CCTV)',
    category: 'Säkerhetssystem (Brand, Passersystem, Inbrott, CCTV)',
    parentCode: 'EV',
    scope: 'IP-baserade kameror, videohanteringssystem (VMS) och digital bildlagring.',
    typicalMaterials: ['Kupol- och bulletkameror med IR-belysning', 'PoE-injektorer', 'RAID-lagringsservrar'],
    iec81346Equivalents: ['-BG', '-KF'],
    iec61355Documents: ['&FS', '&FN'],
    raNotes: 'Ljusförhållanden och motljuskompensation (WDR) ska beaktas vid kameraval.',
  },
  {
    code: 'EY',
    system: 'AMA EL',
    title: 'Styr- och övervakningssystem (Fastighetsautomation)',
    category: 'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
    scope: 'Undercentraler, programmerbara DUC, fältbussar, givare och manöverorgan för byggnadens teknik.',
    typicalMaterials: ['DUC/DDC', 'Temperaturgivare', 'Tryckgivare', 'Ställdon', 'Kopplingsur'],
    iec81346Equivalents: ['=K', '-KF', '-BP', '-BT'],
    iec61355Documents: ['&FS', '&FE', '&WD', '&FL'],
    raNotes: 'Samordnas nära med VVS- och ventilationsentreprenören via gränsdragningslista (tabell över vem som levererar, kopplar och driftsätter).',
  },
  {
    code: 'EYB',
    system: 'AMA EL',
    title: 'Automationscentraler och DUC-enheter',
    category: 'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
    parentCode: 'EY',
    scope: 'Digitala undercentraler (DDC) för processtyrning av ventilation, värmeväxlare och kyla.',
    typicalMaterials: ['DUC-kontroller', 'I/O-moduler med hand/noll/auto-omkopplare', '24V transformator/nätaggregat'],
    iec81346Equivalents: ['-KF', '+W_DUC'],
    iec61355Documents: ['&FE', '&FS', '&FA'],
    raNotes: 'Hand-omkopplare på analoga och digitala utgångar ska finnas för att möjliggöra manuell nöddrift vid styrhaveri.',
  },
  {
    code: 'EYC',
    system: 'AMA EL',
    title: 'Fältbussar och nätverk i automationssystem',
    category: 'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
    parentCode: 'EY',
    scope: 'Industriella bussar för kommunikation mellan DUC, frekvensomriktare, VVS-pumpar och rumsenheter.',
    typicalMaterials: ['BACnet/IP', 'Modbus RTU över RS485', 'M-Bus kabel', 'Termineringsmotstånd'],
    iec81346Equivalents: ['-W', '-KF'],
    iec61355Documents: ['&WD', '&FS'],
    raNotes: 'Skärmen på RS485-fältbuss får endast jordas i master-änden för att förhindra jordslingor och kommunikationsfel.',
  },
  {
    code: 'EYD',
    system: 'AMA EL',
    title: 'Givare och mätutrustning för styrning',
    category: 'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
    parentCode: 'EY',
    scope: 'Sensorer för mätning av temperatur, differenstryck, luftflöde, relativ fuktighet och koldioxid (CO2).',
    typicalMaterials: ['Dykgivare för rör PT1000', 'Kanaltemperaturgivare', 'Trycktransmittrar 0-10V/4-20mA', 'CO2-rumsgivare'],
    iec81346Equivalents: ['-BT', '-BP', '-BQ'],
    iec61355Documents: ['&FS', '&FL', '&FA'],
    raNotes: 'Montera dykgivare med värmeledande pasta i dykrör för snabb och noggrann temperaturmätning.',
  },
  {
    code: 'EYE',
    system: 'AMA EL',
    title: 'Ställdon och ventiler för automation',
    category: 'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
    parentCode: 'EY',
    scope: 'Elektriska reglermotorer för ventilationsspjäll, värmeventiler och kylventiler.',
    typicalMaterials: ['Spjällställdon 24V AC/DC 0-10V', 'Ventilställdon med nödställningsfjäder', 'Belimo / Siemens don'],
    iec81346Equivalents: ['-QM', '-MB'],
    iec61355Documents: ['&FS', '&FA'],
    raNotes: 'Fjäderåtergång krävs på ställdon för frysskydd vid värmebatterier och friskluftsspjäll vid strömavbrott.',
  },
  {
    code: 'EYF',
    system: 'AMA EL',
    title: 'Övergripande styr- och övervakningssystem (BMS/SCADA)',
    category: 'Styr- & Övervakningssystem (Fastighetsautomation & SCADA)',
    parentCode: 'EY',
    scope: 'Central programvara med visualisering, schemaläggning, larmkvittering och energirapporter.',
    typicalMaterials: ['SCADA-server', 'Webbklient HTML5', 'SQL-databaser för trendloggning'],
    iec81346Equivalents: ['-KF', '-WD'],
    iec61355Documents: ['&WD', '&FS'],
    raNotes: 'Standardprotokoll (BACnet/IP) ska användas för att undvika inlåsning i proprietära system.',
  },

  // ==========================================
  // KAPITEL Y - MÄRKNING, KONTROLL & DOKUMENTATION
  // ==========================================
  {
    code: 'YKB',
    system: 'AMA EL',
    title: 'Märkning och skyltning av elinstallationer',
    category: 'Märkning, Provning & Dokumentation (Y)',
    scope: 'Märkning av kablar, ledare, plintar, kapslingar, brytare, uttag och utrustning.',
    typicalMaterials: ['Graverade plastskyltar (Resopal)', 'Kabelmärkning Partex', 'Varningsskyltar för högspänning/solceller'],
    iec81346Equivalents: ['-W', '+W', '=W'],
    iec61355Documents: ['&FN', '&FS', '&FA'],
    raNotes: 'Märkningen ska överensstämma exakt med ritningarnas och schemanas beteckningar enligt IEC 81346.',
  },
  {
    code: 'YKC',
    system: 'AMA EL',
    title: 'Drift- och underhållsinstruktioner (DU-instruktioner)',
    category: 'Märkning, Provning & Dokumentation (Y)',
    scope: 'Dokumentation för fastighetens fortlöpande drift, felsökning, underhåll och reservdelar.',
    typicalMaterials: ['Digital DU-pärm', 'Produktblad', 'Serviceinstruktioner', 'Underhållsscheman'],
    iec81346Equivalents: ['=W'],
    iec61355Documents: ['&MA', '&MB', '&MC'],
    raNotes: 'Levereras normalt digitalt i PDF-format strukturerat enligt BSAB-koder eller CoClass.',
  },
  {
    code: 'YKD',
    system: 'AMA EL',
    title: 'Relationshandlingar och ritningar',
    category: 'Märkning, Provning & Dokumentation (Y)',
    scope: 'Relationsritningar, kretsscheman, yttre kretsscheman och apparatlistor som visar verkligt utförande.',
    typicalMaterials: ['CAD-filer (DWG/BIM)', 'Relationsritningar i PDF', 'Kabellistor och apparatlistor'],
    iec81346Equivalents: ['=W'],
    iec61355Documents: ['&AA', '&FS', '&FN', '&FA', '&FL'],
    raNotes: 'Rättningar och avvikelser som uppstått under bygget ska föras in före slutbesiktning.',
  },
  {
    code: 'YL',
    system: 'AMA EL',
    title: 'Provning, kontroll och drifttagning',
    category: 'Märkning, Provning & Dokumentation (Y)',
    scope: 'Kontroll före idrifttagning, isolationsresistansprovning, kontinuitetsmätning och skyddsprovning.',
    typicalMaterials: ['Installationsprovare (Megger/Fluke)', 'Kontrollprotokoll SS 436 40 00', 'Jordtagsmätare'],
    iec81346Equivalents: ['-PE', '-QA', '-FC'],
    iec61355Documents: ['&PM', '&PL'],
    raNotes: 'Protokoll över genomförd egenkontroll och mätvärden (kontinuitet PE, isolationsresistans > 1 MΩ, slingimpedans, jordfelsbrytare utlösningstid och ström) ska signeras.',
  },

  // ==========================================
  // AMA SAMORDNING (EL / VVS / STYR)
  // ==========================================
  {
    code: 'PB',
    system: 'AMA Samordning',
    title: 'Pumpar och pumpanläggningar (Gränsdragning)',
    category: 'Drivsystem, Motorer & Kraftuttag',
    scope: 'Elektrisk matning, arbetsbrytare, startutrustning och styrsignaler till cirkulations- och tryckstegringspumpar.',
    typicalMaterials: ['Cirkulationspumpar', 'Säkerhetsbrytare', '0-10V hastighetsstyrning', 'Drift- och felindikering'],
    iec81346Equivalents: ['-MA', '-QM'],
    iec61355Documents: ['&FS'],
    raNotes: 'VVS levererar normalt pumpen; El levererar arbetsbrytare, kablage och inkoppling; Styr kopplar styrsignal och fältbuss.',
  },
  {
    code: 'PD',
    system: 'AMA Samordning',
    title: 'Fläktar och luftbehandlingsaggregat (Gränsdragning)',
    category: 'Drivsystem, Motorer & Kraftuttag',
    scope: 'Matning och styrning av till- och frånluftsfläktar, brandgasspjäll och värmeväxlare.',
    typicalMaterials: ['Kammarfläktar med EC-motorer', 'Arbetsbrytare', 'Tryckgivare för filtervakt', 'Brandspjäll'],
    iec81346Equivalents: ['-MA', '-QM', '-BP'],
    iec61355Documents: ['&FS', '&WC'],
    raNotes: 'Gränsdragning mellan aggregatets interna automatik och byggnadens övergripande styrsystem ska definieras i systemhandling.',
  },
];

export const searchAmaBsa = (
  query: string,
  selectedSystem: string = 'Alla',
  selectedCategory: string = 'Alla'
): AmaBsaEntry[] => {
  const cleanQuery = query.trim().toLowerCase();

  return AMA_BSA_ENTRIES.filter((entry) => {
    // System filter
    if (selectedSystem !== 'Alla' && entry.system !== selectedSystem) {
      return false;
    }

    // Category filter
    if (selectedCategory !== 'Alla' && entry.category !== selectedCategory) {
      return false;
    }

    // If no query, matches
    if (!cleanQuery) return true;

    // Search matches code, title, scope, materials, raNotes, iec equivalents
    const codeMatch = entry.code.toLowerCase().includes(cleanQuery);
    const titleMatch = entry.title.toLowerCase().includes(cleanQuery);
    const scopeMatch = entry.scope.toLowerCase().includes(cleanQuery);
    const notesMatch = entry.raNotes ? entry.raNotes.toLowerCase().includes(cleanQuery) : false;
    const materialMatch = entry.typicalMaterials.some((m) =>
      m.toLowerCase().includes(cleanQuery)
    );
    const iec81346Match = entry.iec81346Equivalents
      ? entry.iec81346Equivalents.some((iec) => iec.toLowerCase().includes(cleanQuery))
      : false;
    const iec61355Match = entry.iec61355Documents
      ? entry.iec61355Documents.some((doc) => doc.toLowerCase().includes(cleanQuery))
      : false;

    return (
      codeMatch ||
      titleMatch ||
      scopeMatch ||
      notesMatch ||
      materialMatch ||
      iec81346Match ||
      iec61355Match
    );
  });
};
