/**
 * Complete database and lookup functions for IEC 81346 / SS-EN IEC 81346-2
 * Reference Designations (Postbeteckningar / Referensbeteckningar i elscheman)
 * Specifically Table 2 (Two-letter codes) and Table 1 (Main classes).
 */

export interface Iec81346Entry {
  code: string; // e.g. "QA", "FD", "BT"
  mainClass: string; // e.g. "Q", "F", "B"
  swedishName: string; // Svensk benämning
  englishName: string; // IEC official English designation
  category: 'Kraft & Omkoppling' | 'Skydd' | 'Givare & Sensorer' | 'Styrning & Relä' | 'Motorer' | 'Manöver' | 'Transformering' | 'Anslutning' | 'Kablar & Ledare' | 'Mätning & Indikering' | 'Värme & Ljus' | 'Energilagring' | 'Kraftkällor' | 'Kapsling & Stativ' | 'Begränsning';
  definition: string; // Standarddefinition av ändamål/uppgift
  examples: string[]; // Vanliga komponenter och produkter i svensk el- och automationsbransch
  typicalPrefix: string; // Typisk postbeteckning på kretsschema t.ex. "-QA1"
  legacyComparison?: string; // Jämförelse med äldre IEC 61346 eller svensk praxis
  colorClass: string; // Tailwind styling accents
}

export interface IecMainClass {
  letter: string;
  name: string;
  taskDefinition: string;
  category: string;
  description: string;
}

export const IEC_MAIN_CLASSES: IecMainClass[] = [
  {
    letter: 'A',
    name: 'Två eller flera ändamål / Sammanbyggda system',
    taskDefinition: 'Två eller flera ändamål eller uppgifter',
    category: 'Sammansatt',
    description: 'Enheter med flera olika integrerade funktioner som inte domineras av en enskild klass (t.ex. multifunktionsenheter).',
  },
  {
    letter: 'B',
    name: 'Givare, sensorer & mätomvandlare',
    taskDefinition: 'Omvandla en insignal (fysikalisk storhet) till en signal för vidare bearbetning',
    category: 'Givare & Sensorer',
    description: 'Detektorer, gränslägesgivare, fotoceller, temperatur- och tryckgivare som skickar mätsignaler till styrsystem.',
  },
  {
    letter: 'C',
    name: 'Lagra energi, information eller material',
    taskDefinition: 'Lagra energi, information eller material',
    category: 'Energilagring',
    description: 'Kondensatorer, ackumulatorer, batterier, minnen och tankar.',
  },
  {
    letter: 'E',
    name: 'Strålnings- och termisk energi',
    taskDefinition: 'Ge strålnings- eller termisk energi',
    category: 'Värme & Ljus',
    description: 'Belysningsarmaturer, lampor, värmeelement, elpatroner och kylelement.',
  },
  {
    letter: 'F',
    name: 'Direkt skydd av personer, utrustning eller nät',
    taskDefinition: 'Direkt skydd av flöde av energi, signaler, personer eller utrustning mot farliga tillstånd',
    category: 'Skydd',
    description: 'Säkringar, dvärgbrytare, överspänningsskydd, motorskydd och jordfelsbrytare.',
  },
  {
    letter: 'G',
    name: 'Initiera energiflöde / Kraftkällor',
    taskDefinition: 'Initiera ett flöde av energi eller material',
    category: 'Kraftkällor',
    description: 'Generatorer, nätaggregat (strömförsörjning), solceller och UPS.',
  },
  {
    letter: 'K',
    name: 'Bearbeta signaler och information (Styrning)',
    taskDefinition: 'Bearbeta (processa) signaler eller information',
    category: 'Styrning & Relä',
    description: 'Hjälpreläer, kontaktorer för styrsignaler, tidreläer, säkerhetsreläer och PLC-styrningar.',
  },
  {
    letter: 'M',
    name: 'Mekanisk drivenergi / Motorer',
    taskDefinition: 'Ge mekanisk energi (rörelseenergi)',
    category: 'Motorer',
    description: 'Elmotorer, servomotorer, linjära ställdon och pumpar.',
  },
  {
    letter: 'P',
    name: 'Presentera information / Mätare & Indikering',
    taskDefinition: 'Presentera information i visuell eller auditiv form',
    category: 'Mätning & Indikering',
    description: 'Amperemetrar, voltmetrar, signallampor, sirener, displayer och HMI-paneler.',
  },
  {
    letter: 'Q',
    name: 'Kontrollerad omkoppling av elektrisk kraft',
    taskDefinition: 'Kontrollerad till-, från- eller omkoppling av ett flöde av energi',
    category: 'Kraft & Omkoppling',
    description: 'Effektbrytare, kontaktorer i huvudströmkretsar, lastfrånskiljare och motorskyddsbrytare.',
  },
  {
    letter: 'R',
    name: 'Begränsa eller stabilisera energiflöde',
    taskDefinition: 'Begränsa eller stabilisera rörelse eller flöde av energi',
    category: 'Begränsning',
    description: 'Motstånd, resistorer, dioder, drosslar, EMC-filter och bromsmotstånd.',
  },
  {
    letter: 'S',
    name: 'Omvandla manuell manöver till signal',
    taskDefinition: 'Omvandla en manuell manöver till en signal för vidare bearbetning',
    category: 'Manöver',
    description: 'Tryckknappar, vridomkopplare, nödstoppsknappar och fotpedaler.',
  },
  {
    letter: 'T',
    name: 'Transformera energi eller signaler',
    taskDefinition: 'Omvandla energi, signaler eller material med bibehållen grundkaraktär',
    category: 'Transformering',
    description: 'Krafttransformatorer, manövertransformatorer, frekvensomriktare, mätomvandlare och likriktare.',
  },
  {
    letter: 'U',
    name: 'Bära och hålla objekt i definierat läge',
    taskDefinition: 'Hålla objekt i ett definierat läge i rummet',
    category: 'Kapsling & Stativ',
    description: 'Apparatskåp, kapslingar, DIN-skenor, stativ och kabelstegar.',
  },
  {
    letter: 'W',
    name: 'Leda och transportera energi och signaler',
    taskDefinition: 'Leda eller styra energi, signaler, material eller produkter',
    category: 'Kablar & Ledare',
    description: 'Kraftkablar, signalkablar, busskablar, fasskenor och fiberoptik.',
  },
  {
    letter: 'X',
    name: 'Ansluta och förbinda objekt',
    taskDefinition: 'Ansluta eller förbinda objekt mekaniskt eller elektriskt',
    category: 'Anslutning',
    description: 'Radplintar, kopplingsplintar, stickproppar, vägguttag och kontaktdon.',
  },
];

export const IEC_TABLE_2_ENTRIES: Iec81346Entry[] = [
  // --- KLASS Q: Kontrollerad omkoppling av kraft ---
  {
    code: 'QA',
    mainClass: 'Q',
    swedishName: 'Effektbrytare / Strömbrytare i kraftkrets',
    englishName: 'Circuit breaker for power circuits',
    category: 'Kraft & Omkoppling',
    definition: 'Mekanisk brytare kapabel att sluta, leda och bryta strömmar under normala kretsförhållanden samt vid kortslutning och överlast.',
    examples: ['Effektbrytare (MCCB)', 'Luftbrytare (ACB)', 'Kompaktbrytare i ställverk', 'Huvudbrytare med magnetisk/termisk brytning'],
    typicalPrefix: '-QA1',
    legacyComparison: 'Betecknades ofta Q1 eller -Q1 i äldre IEC 61346.',
    colorClass: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  },
  {
    code: 'QB',
    mainClass: 'Q',
    swedishName: 'Frånskiljare',
    englishName: 'Disconnector',
    category: 'Kraft & Omkoppling',
    definition: 'Mekanisk kopplingsapparat som i öppet läge uppfyller kraven för frånskiljning. Får normalt endast manövreras i spänningslöst eller obelastat tillstånd.',
    examples: ['Frånskiljare utan lastbrytförmåga', 'Högspänningsfrånskiljare', 'Knivfrånskiljare i ställverk'],
    typicalPrefix: '-QB1',
    legacyComparison: 'Tidigare klass Q.',
    colorClass: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  },
  {
    code: 'QC',
    mainClass: 'Q',
    swedishName: 'Kontaktor (Kraftkrets / Motorkontaktor)',
    englishName: 'Contactor for power switching',
    category: 'Kraft & Omkoppling',
    definition: 'Fjärrmanövrerad mekanisk kopplingsapparat med endast ett stabilt viloläge, konstruerad för frekvent koppling av normala driftströmmar i kraftled.',
    examples: ['Motorkontaktor (huvudkontakter i kraftled)', 'Värmekontaktor', 'Kondensatorkontaktor'],
    typicalPrefix: '-QC1 (eller -KM1 vid styrfokus)',
    legacyComparison: 'Mycket vanligt betecknad -KM i äldre elscheman. IEC 81346 klassar den under QC om funktionen är kraftomkoppling.',
    colorClass: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  },
  {
    code: 'QD',
    mainClass: 'Q',
    swedishName: 'Lastfrånskiljare / Säkerhetsbrytare',
    englishName: 'Switch-disconnector',
    category: 'Kraft & Omkoppling',
    definition: 'Manöverbrytare som uppfyller kraven för både lastbrytning (kan bryta märkström) och frånskiljning (synligt brytställe eller säker frånskiljning).',
    examples: ['Säkerhetsbrytare vid motor', 'Arbetsbrytare', 'Huvudbrytare i apparatskåp', 'Lastfrånskiljare med vred'],
    typicalPrefix: '-QD1',
    legacyComparison: 'Tidigare ofta -Q eller -S i äldre anläggningar.',
    colorClass: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  },
  {
    code: 'QE',
    mainClass: 'Q',
    swedishName: 'Jordningskopplare',
    englishName: 'Earthing switch',
    category: 'Kraft & Omkoppling',
    definition: 'Kopplingsapparat för att jorda och kortsluta delar av en krets under säkra förhållanden inför arbete.',
    examples: ['Jordningskopplare i mellanspänningsställverk', 'Snabbjordare'],
    typicalPrefix: '-QE1',
    legacyComparison: 'Tidigare ofta -Q.',
    colorClass: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  },
  {
    code: 'QF',
    mainClass: 'Q',
    swedishName: 'Motorskyddsbrytare',
    englishName: 'Motor starter / Motor protection circuit breaker',
    category: 'Kraft & Omkoppling',
    definition: 'Kombinerad manuell startapparat och överströms-/kortslutningsskydd för elmotorer.',
    examples: ['Motorskyddsbrytare med vred (t.ex. PKZM, GV2)', 'Handmanövrerat motorskydd med fasbortfallsskydd'],
    typicalPrefix: '-QF1',
    legacyComparison: 'Betecknades ofta -QM eller -Q i äldre scheman.',
    colorClass: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  },
  {
    code: 'QK',
    mainClass: 'Q',
    swedishName: 'Halvledarkontaktor / Tyristorställare',
    englishName: 'Solid-state contactor',
    category: 'Kraft & Omkoppling',
    definition: 'Elektronisk kontaktor utan rörliga delar för snabb och slitfri inkoppling av värmelaster eller motorer.',
    examples: ['Solid State Relä (SSR) för kraftkretsar', 'Tyristoromkopplare för värmepatroner'],
    typicalPrefix: '-QK1',
    legacyComparison: 'Tidigare ofta -K eller -V.',
    colorClass: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  },
  {
    code: 'QM',
    mainClass: 'Q',
    swedishName: 'Mjukstartare / Startapparat',
    englishName: 'Motor starter / Softstarter',
    category: 'Kraft & Omkoppling',
    definition: 'Apparat för kontrollerad rampning av spänning och ström vid start och stopp av asynkronmotorer.',
    examples: ['Elektronisk mjukstartare (Softstarter)', 'Y/D-startkombination'],
    typicalPrefix: '-QM1',
    legacyComparison: 'Ofta betecknad -G eller -U i äldre system.',
    colorClass: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
  },

  // --- KLASS F: Direkt skydd ---
  {
    code: 'FA',
    mainClass: 'F',
    swedishName: 'Snabbt överströmsskydd / Finsäkring',
    englishName: 'Fast-acting overcurrent protection',
    category: 'Skydd',
    definition: 'Skyddsanordning avsedd för mycket snabb bortkoppling av känslig elektronik vid överström.',
    examples: ['Finsäkring 5x20 mm', 'Glassäkring på kretskort eller i plint', 'Elektronisk säkring (e-fuse)'],
    typicalPrefix: '-FA1',
    legacyComparison: 'Betecknades -F i äldre standard.',
    colorClass: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
  },
  {
    code: 'FB',
    mainClass: 'F',
    swedishName: 'Överlastskydd / Termiskt relä (Bimetall)',
    englishName: 'Overload protection device',
    category: 'Skydd',
    definition: 'Skyddsenhet som reagerar på långvarig måttlig överbelastning genom temperaturstegring.',
    examples: ['Termiskt överströmsrelä till kontaktor', 'Bimetallrelä', 'Termistorskyddsrelä i motorlindning'],
    typicalPrefix: '-FB1',
    legacyComparison: 'Mycket ofta betecknat -F eller -FR i äldre svenska ritningar.',
    colorClass: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
  },
  {
    code: 'FC',
    mainClass: 'F',
    swedishName: 'Smältsäkring (Diazed / NH)',
    englishName: 'Fuse / Melting fuse',
    category: 'Skydd',
    definition: 'Självbrytande komponent där en smältledare smälter vid för hög ström för att bryta kretsen permanent.',
    examples: ['Gängsäkring Diazed (DII 10A-25A, DIII 35A-63A)', 'Knivsäkring NH00 / NH1', 'Cylindersäkring 10x38 mm'],
    typicalPrefix: '-FC1',
    legacyComparison: 'Standardbeteckning för smältsäkringar. Ersätter det generella -F.',
    colorClass: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
  },
  {
    code: 'FD',
    mainClass: 'F',
    swedishName: 'Dvärgbrytare / Automatsäkring (MCB)',
    englishName: 'Miniature circuit breaker (MCB)',
    category: 'Skydd',
    definition: 'Återställbar elektromagnetisk och termisk skyddsanordning för skydd av ledningar mot överlast och kortslutning.',
    examples: ['Dvärgbrytare typ B, C eller D (1-pol, 2-pol, 3-pol, 4-pol)', 'Normcentralens automatsäkringar'],
    typicalPrefix: '-FD1',
    legacyComparison: 'I äldre ritningar betecknades MCB ofta som -F eller -Q.',
    colorClass: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
  },
  {
    code: 'FE',
    mainClass: 'F',
    swedishName: 'Jordfelsbrytare / Personskydd (RCD / RCBO)',
    englishName: 'Residual current device (RCD / RCBO)',
    category: 'Skydd',
    definition: 'Skyddsapparat som känner av differensström mellan faser och neutralledare för att skydda mot elchock och brand.',
    examples: ['Jordfelsbrytare 30 mA personskydd', 'Brandskydds-JFB 300 mA', 'Personskyddsautomat (kombinerad MCB + JFB)'],
    typicalPrefix: '-FE1',
    legacyComparison: 'Betecknades ofta -Q, -F eller -JFB i äldre svenska ritningar.',
    colorClass: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
  },
  {
    code: 'FF',
    mainClass: 'F',
    swedishName: 'Överspänningsskydd / Åskskydd (SPD)',
    englishName: 'Surge protective device (SPD)',
    category: 'Skydd',
    definition: 'Skyddskomponent för att avleda transienta överspänningar orsakade av blixtnedslag eller nätomkopplingar.',
    examples: ['Grovskydd / Mellanskydd typ 1 och typ 2 i central', 'Varistorbaserat finskydd typ 3', 'Gnistsgap / Gasurladdningsrör'],
    typicalPrefix: '-FF1',
    legacyComparison: 'Betecknades förr ofta -F eller -R.',
    colorClass: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
  },
  {
    code: 'FG',
    mainClass: 'F',
    swedishName: 'Säkerhetsgränsskydd / Nödstoppskrets',
    englishName: 'Safety protection device',
    category: 'Skydd',
    definition: 'Direktverkande skyddskomponent i säkerhetskretsar för att förhindra personskada vid olycka.',
    examples: ['Linsäkerhetsbrytare längs transportband', 'Mekanisk säkerhetsbrytare med lås'],
    typicalPrefix: '-FG1',
    legacyComparison: 'Klassades tidigare ofta under -S.',
    colorClass: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
  },
  {
    code: 'FP',
    mainClass: 'F',
    swedishName: 'Ljusbågsvakt / Ljusbågsdetektor (AFDD)',
    englishName: 'Arc fault detection device (AFDD)',
    category: 'Skydd',
    definition: 'Skyddsenhet som detekterar serie- eller parallelljusbågar orsakade av skadade kablar eller glappkontakt.',
    examples: ['Ljusbågsdetektor (AFDD)', 'Ljusbågsvakt med optiska sensorer i ställverk'],
    typicalPrefix: '-FP1',
    legacyComparison: 'Ny modern skyddskategori.',
    colorClass: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
  },
  {
    code: 'FS',
    mainClass: 'F',
    swedishName: 'Säkringslastfrånskiljare',
    englishName: 'Fuse-switch disconnector',
    category: 'Skydd',
    definition: 'Kombinerad brytare och säkringshållare där säkringarna bryts samtidigt med manöverhandtaget.',
    examples: ['Säkringslastfrånskiljare för NH-knivsäkringar i servisskåp', 'D02-lastbrytare'],
    typicalPrefix: '-FS1',
    legacyComparison: 'Tidigare klass -Q eller -F.',
    colorClass: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
  },

  // --- KLASS B: Givare och sensorer ---
  {
    code: 'BA',
    mainClass: 'B',
    swedishName: 'Spänningssensor / Spänningsvakt',
    englishName: 'Voltage sensor / Voltage transducer',
    category: 'Givare & Sensorer',
    definition: 'Omvandlar elektrisk spänning till mätsignal för övervakning eller styrning.',
    examples: ['Spänningstransducer', 'Fasföljdsvakt / Underspänningsrelä', 'Mätdelar i nätövervakning'],
    typicalPrefix: '-BA1',
    legacyComparison: 'Tidigare ofta -B eller -U.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BB',
    mainClass: 'B',
    swedishName: 'Strömgivare / Mätströmtransformator',
    englishName: 'Current sensor / Current transducer',
    category: 'Givare & Sensorer',
    definition: 'Mäter strömflöde och omvandlar till normerad signal (t.ex. 4-20 mA eller 0-10 V).',
    examples: ['Strömvakt för motorbelastning', 'Rogowski-spole', 'Hall-effekt strömsensor för DC'],
    typicalPrefix: '-BB1',
    legacyComparison: 'Observera skillnad mot ren mättransformator (-TA).',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BE',
    mainClass: 'B',
    swedishName: 'Positionsgivare / Lägesgivare (Induktiv / Kapacitiv)',
    englishName: 'Position sensor / Proximity sensor',
    category: 'Givare & Sensorer',
    definition: 'Registrerar närvaro, position eller förskjutning av ett objekt utan mekanisk kontakt.',
    examples: ['Induktiv givare (avkänner metall)', 'Kapacitiv givare (avkänner vätska/plast)', 'Ultraljudsgivare för avstånd', 'Magnetbrytare'],
    typicalPrefix: '-BE1',
    legacyComparison: 'Mycket vanligt betecknad -B i automationsscheman.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BF',
    mainClass: 'B',
    swedishName: 'Flödesgivare / Flödesmätare',
    englishName: 'Flow sensor',
    category: 'Givare & Sensorer',
    definition: 'Mäter volym- eller massflöde av gaser eller vätskor i rörsystem.',
    examples: ['Magnetisk-induktiv flödesmätare', 'Paddelflödesvakt i kylkrets', 'Massflödesmätare'],
    typicalPrefix: '-BF1',
    legacyComparison: 'Tidigare klass -B.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BG',
    mainClass: 'B',
    swedishName: 'Vibrations- & Accelerationsgivare',
    englishName: 'Acceleration / Vibration sensor',
    category: 'Givare & Sensorer',
    definition: 'Detekterar vibrationer och accelerationer för tillståndsövervakning av roterande maskiner.',
    examples: ['Vibrationsgivare på motorlager', 'Accelerometer för lagerövervakning'],
    typicalPrefix: '-BG1',
    legacyComparison: 'Tidigare klass -B.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BL',
    mainClass: 'B',
    swedishName: 'Nivågivare / Nivåvakt',
    englishName: 'Level sensor / Level switch',
    category: 'Givare & Sensorer',
    definition: 'Detekterar vätske- eller bulknivå i tankar, behållare och pumpgropar.',
    examples: ['Dränkbar tryckgivare i pumpbrunn', 'Flottörvippa / Nivåvippa', 'Radar-/mikrovågsnivåmätare'],
    typicalPrefix: '-BL1',
    legacyComparison: 'Ofta kallad nivåvakt -B i VA-installationer.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BM',
    mainClass: 'B',
    swedishName: 'Fuktgivare (Hygrometer)',
    englishName: 'Humidity / Moisture sensor',
    category: 'Givare & Sensorer',
    definition: 'Mäter relativ eller absolut luftfuktighet i lokaler eller ventilationskanaler.',
    examples: ['Kanalmonterad fuktgivare i ventilation', 'Skåphygrostat för apparatskåp'],
    typicalPrefix: '-BM1',
    legacyComparison: 'Tidigare klass -B.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BP',
    mainClass: 'B',
    swedishName: 'Tryckgivare / Pressostat',
    englishName: 'Pressure sensor / Pressure switch',
    category: 'Givare & Sensorer',
    definition: 'Omvandlar mekaniskt gastryck eller vätsketryck till elektrisk signal eller kontaktfunktion.',
    examples: ['Trycktransmitter 4-20 mA i rörsystem', 'Pressostat för kompressorstart', 'Differenstryckvakt över ventilationsfilter'],
    typicalPrefix: '-BP1',
    legacyComparison: 'Mycket vanlig inom VVS/Fastighetsautomation.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BQ',
    mainClass: 'B',
    swedishName: 'Kvalitetsgivare (pH / Konduktivitet / Gas)',
    englishName: 'Quality sensor (Chemical / Environmental)',
    category: 'Givare & Sensorer',
    definition: 'Mäter kemiska egenskaper eller föroreningar i medier.',
    examples: ['pH-elektrod', 'Konduktivitetsmätare', 'CO2-givare i konferensrum'],
    typicalPrefix: '-BQ1',
    legacyComparison: 'Tidigare klass -B.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BS',
    mainClass: 'B',
    swedishName: 'Varvtalsgivare / Pulsgivare (Encoder)',
    englishName: 'Rotational speed sensor / Tachometer',
    category: 'Givare & Sensorer',
    definition: 'Registrerar rotationshastighet, vridningsvinkel eller antal varv på en axel.',
    examples: ['Inkrementell pulsgivare', 'Absolutgivare på servomotor', 'Kuggkransgivare för varvtalsmätning'],
    typicalPrefix: '-BS1',
    legacyComparison: 'Ofta betecknad -B eller -G.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BT',
    mainClass: 'B',
    swedishName: 'Temperaturgivare / Termostat',
    englishName: 'Temperature sensor / Thermostat',
    category: 'Givare & Sensorer',
    definition: 'Känner av temperatur och omvandlar den till resistansförändring, spänning eller kontaktfunktion.',
    examples: ['PT100 / PT1000 resistanstemperaturgivare', 'Termoelement typ K', 'Rumstermostat / Skåptermostat', 'NTC/PTC dykgivare'],
    typicalPrefix: '-BT1',
    legacyComparison: 'Klassisk standardkod för temperatur inom svensk industri.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BW',
    mainClass: 'B',
    swedishName: 'Kraftgivare / Lastcell (Våg)',
    englishName: 'Weight / Force sensor / Load cell',
    category: 'Givare & Sensorer',
    definition: 'Mäter mekanisk drag- eller tryckkraft, spänning eller vikt med trådtöjningsgivare.',
    examples: ['Lastcell under silobehållare', 'Bandvågsgivare', 'Momentmätare'],
    typicalPrefix: '-BW1',
    legacyComparison: 'Tidigare klass -B.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },
  {
    code: 'BY',
    mainClass: 'B',
    swedishName: 'Optisk givare / Fotocell / Ljusridå',
    englishName: 'Optical sensor / Light barrier',
    category: 'Givare & Sensorer',
    definition: 'Detekterar objekt eller ljusmängd med hjälp av ljusstrålar (synligt ljus, IR eller laser).',
    examples: ['Fotocell reflex / sändare-mottagare', 'Säkerhetsljusridå runt robotcell', 'Skymningsrelä (ljussensor)', 'Färg- och kontrastgivare'],
    typicalPrefix: '-BY1',
    legacyComparison: 'Mycket vanlig inom maskinsäkerhet och paketering.',
    colorClass: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
  },

  // --- KLASS K: Bearbeta signaler och information (Styrning) ---
  {
    code: 'KA',
    mainClass: 'K',
    swedishName: 'Hjälprelä / Hjälpkontaktor',
    englishName: 'Auxiliary relay / Contactor relay',
    category: 'Styrning & Relä',
    definition: 'Relä avsett för multiplikation, förstärkning eller logisk koppling av styrsignaler i svagströmskretsar.',
    examples: ['Mellanrelä (sockelrelä 24V DC / 230V AC)', 'Hjälpkontaktor med 4 slutande kontakter', 'Interface-relä'],
    typicalPrefix: '-KA1',
    legacyComparison: 'Standardkod i alla svenska kopplingsscheman.',
    colorClass: 'text-cyan-400 bg-cyan-500/10 border-cyan-500/30',
  },
  {
    code: 'KB',
    mainClass: 'K',
    swedishName: 'Bistabilt relä / Impulsrelä',
    englishName: 'Bistable relay / Latching relay',
    category: 'Styrning & Relä',
    definition: 'Relä som ändrar tillstånd vid en kort elektrisk impuls och behåller sitt nya läge utan kontinuerlig styrspänning.',
    examples: ['Impulsrelä för trappbelysning', 'Stegrelä för belysningsstyrning i korridorer'],
    typicalPrefix: '-KB1',
    legacyComparison: 'Kallades ofta impulsrelä eller trapprelä.',
    colorClass: 'text-cyan-400 bg-cyan-500/10 border-cyan-500/30',
  },
  {
    code: 'KF',
    mainClass: 'K',
    swedishName: 'Tidrelä (Elektroniskt / Mekaniskt)',
    englishName: 'Time relay / Timer',
    category: 'Styrning & Relä',
    definition: 'Relä med inbyggd tidsfördröjning för tillslag, frånslag, puls eller blinkfunktion.',
    examples: ['Tillslagsfördröjt tidrelä (pådragsfördröjning)', 'Frånslagsfördröjt relä för fläkt eftergång', 'Multifunktionstidrelä'],
    typicalPrefix: '-KF1',
    legacyComparison: 'Betecknades ofta -KT i äldre standard.',
    colorClass: 'text-cyan-400 bg-cyan-500/10 border-cyan-500/30',
  },
  {
    code: 'KH',
    mainClass: 'K',
    swedishName: 'Säkerhetsrelä / Säkerhetsmodul',
    englishName: 'Safety relay / Safety logic unit',
    category: 'Styrning & Relä',
    definition: 'Övervakad reläenhet med tvångsstyrda kontakter för säkert stopp vid nödstopp eller bruten ljusridå (upp till PL e / SIL 3).',
    examples: ['Nödstoppsrelä (t.ex. Jokab RT9, Pilz PNOZ)', 'Tvåhandsrelä för pressar', 'Säkerhets-PLC'],
    typicalPrefix: '-KH1',
    legacyComparison: 'Viktigaste komponenten i maskinsäkerhetskretsar.',
    colorClass: 'text-cyan-400 bg-cyan-500/10 border-cyan-500/30',
  },
  {
    code: 'KM',
    mainClass: 'K',
    swedishName: 'Styrkontaktor / Mindre kontaktor',
    englishName: 'Contactor for control / switching',
    category: 'Styrning & Relä',
    definition: 'Elektromagnetisk kontaktor för omkoppling av elektriska kretsar.',
    examples: ['Kontaktor i manöverkrets', 'Huvudkontaktor när funktionen ses som styrsignal'],
    typicalPrefix: '-KM1',
    legacyComparison: 'Den mest kända koden för kontaktor bland svenska elektriker.',
    colorClass: 'text-cyan-400 bg-cyan-500/10 border-cyan-500/30',
  },
  {
    code: 'KP',
    mainClass: 'K',
    swedishName: 'Räknare / Pulsräknare',
    englishName: 'Counter / Pulse counter',
    category: 'Styrning & Relä',
    definition: 'Enhet som räknar elektriska insignaler och avger signal efter förvalt antal.',
    examples: ['Batchräknare på förpackningslinje', 'Pulsräknare för flödesvolym'],
    typicalPrefix: '-KP1',
    legacyComparison: 'Tidigare klass -K.',
    colorClass: 'text-cyan-400 bg-cyan-500/10 border-cyan-500/30',
  },
  {
    code: 'KT',
    mainClass: 'K',
    swedishName: 'Kopplingsur / Veckour / Astronomiskt ur',
    englishName: 'Time switch / Clock timer',
    category: 'Styrning & Relä',
    definition: 'Elektroniskt eller mekaniskt klockur som sluter eller bryter kretsar vid förutbestämda klockslag eller datum.',
    examples: ['Astronomiskt skymningsur för gatubelysning', 'Veckour för ventilation', 'Digitalt DIN-monterat tidur'],
    typicalPrefix: '-KT1',
    legacyComparison: 'Betecknades ofta -KT.',
    colorClass: 'text-cyan-400 bg-cyan-500/10 border-cyan-500/30',
  },

  // --- KLASS M: Mekanisk energi (Motorer & Ställdon) ---
  {
    code: 'MA',
    mainClass: 'M',
    swedishName: 'Elmotor (Asynkronmotor / Trefasmotor)',
    englishName: 'Electric motor (Induction / AC motor)',
    category: 'Motorer',
    definition: 'Elektrisk maskin som omvandlar växelströmsenergi till mekanisk rotationsenergi på en axel.',
    examples: ['3-fas asynkronmotor 400V (standard industrimotor)', 'Enfas kondensatormotor 230V', 'IE3/IE4 högeffektiv motor'],
    typicalPrefix: '-MA1',
    legacyComparison: 'Klassisk beteckning: Tidigare -M i äldre scheman.',
    colorClass: 'text-violet-400 bg-violet-500/10 border-violet-500/30',
  },
  {
    code: 'MB',
    mainClass: 'M',
    swedishName: 'Likströmsmotor (DC-motor / BLDC)',
    englishName: 'DC motor / Brushless motor',
    category: 'Motorer',
    definition: 'Elektrisk motor matad med likström, med borstar eller elektronisk kommutering.',
    examples: ['Borstlös DC-motor (BLDC)', 'Spjällmotor med DC-drift', 'Truckdrivmotor'],
    typicalPrefix: '-MB1',
    legacyComparison: 'Tidigare klass -M.',
    colorClass: 'text-violet-400 bg-violet-500/10 border-violet-500/30',
  },
  {
    code: 'MC',
    mainClass: 'M',
    swedishName: 'Stegmotor',
    englishName: 'Stepper motor',
    category: 'Motorer',
    definition: 'Motor som roterar i diskreta vinkelsteg vid varje elektrisk puls för exakt positionering utan återkoppling.',
    examples: ['Stegmotor för automatiserade transportbanor och doseringspumpar', 'Ventilpositionerare'],
    typicalPrefix: '-MC1',
    legacyComparison: 'Tidigare klass -M.',
    colorClass: 'text-violet-400 bg-violet-500/10 border-violet-500/30',
  },
  {
    code: 'MD',
    mainClass: 'M',
    swedishName: 'Servomotor',
    englishName: 'Servomotor',
    category: 'Motorer',
    definition: 'Högdynamisk motor med inbyggd pulsgivare/resolver avsedd för sluten positions- och hastighetsreglering.',
    examples: ['AC-servomotor i robot eller CNC-maskin', 'Positioneringsaxel i förpackningsmaskin'],
    typicalPrefix: '-MD1',
    legacyComparison: 'Tidigare klass -M.',
    colorClass: 'text-violet-400 bg-violet-500/10 border-violet-500/30',
  },
  {
    code: 'ME',
    mainClass: 'M',
    swedishName: 'Linjärt ställdon (Ventilställdon / Cylinder)',
    englishName: 'Linear actuator',
    category: 'Motorer',
    definition: 'Elektromekanisk enhet som ger en rak linjär rörelse (skjuta eller dra).',
    examples: ['Ventilställdon för värmeventil / kylventil i fastighet', 'Elektrisk cylinder', 'Spjällställdon (Belimo)'],
    typicalPrefix: '-ME1',
    legacyComparison: 'Betecknades ofta -M eller -Y i äldre fastighetsel.',
    colorClass: 'text-violet-400 bg-violet-500/10 border-violet-500/30',
  },
  {
    code: 'MF',
    mainClass: 'M',
    swedishName: 'Fläktmotor / Apparatskåpsfläkt',
    englishName: 'Fan / Blower motor',
    category: 'Motorer',
    definition: 'Elmotor integrerad med fläkthjul för luftcirkulation eller kylning.',
    examples: ['Kylfläkt i apparatskåp', 'Frånluftsfläkt i ventilationsaggregat', 'Rökgasfläkt'],
    typicalPrefix: '-MF1',
    legacyComparison: 'Betecknades ofta -M.',
    colorClass: 'text-violet-400 bg-violet-500/10 border-violet-500/30',
  },
  {
    code: 'MP',
    mainClass: 'M',
    swedishName: 'Motorpump (Cirkulationspump / Dränkbar pump)',
    englishName: 'Pump motor',
    category: 'Motorer',
    definition: 'Sammanbyggd elektrisk pumpenhet för vätsketransport.',
    examples: ['Cirkulationspump för värmesystem', 'Dränkbar länspump i källare', 'Hydraulpumpmotor'],
    typicalPrefix: '-MP1',
    legacyComparison: 'I VA och VVS mycket ofta betecknad -P eller -M.',
    colorClass: 'text-violet-400 bg-violet-500/10 border-violet-500/30',
  },

  // --- KLASS S: Manuell manöver till signal ---
  {
    code: 'SA',
    mainClass: 'S',
    swedishName: 'Vridomkopplare / Manöverkopplare',
    englishName: 'Selector switch / Rotary switch',
    category: 'Manöver',
    definition: 'Handmanövrerad omkopplare med två eller flera fasta eller återfjädrande lägen.',
    examples: ['Manöverkopplare Manuell - 0 - Auto (Hand/Off/Auto)', 'Lokal/Fjärr-omkopplare', 'Fasväljaromkopplare för voltmeter'],
    typicalPrefix: '-SA1',
    legacyComparison: 'Mycket vanlig på skåpsdörrar i ställverk.',
    colorClass: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30',
  },
  {
    code: 'SB',
    mainClass: 'S',
    swedishName: 'Tryckknapp (Manöverknapp)',
    englishName: 'Pushbutton switch',
    category: 'Manöver',
    definition: 'Återfjädrande eller låsande knapp för manuell start, stopp eller kvittering.',
    examples: ['Startknapp (grön, sluter)', 'Stoppknapp (röd, bryter)', 'Kvitteringsknapp för larm', 'Ljusknapp med impulsfjäder'],
    typicalPrefix: '-SB1',
    legacyComparison: 'Standardkod för tryckknappar. Ersätter gamla -S.',
    colorClass: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30',
  },
  {
    code: 'SC',
    mainClass: 'S',
    swedishName: 'Nyckelbrytare',
    englishName: 'Key-operated switch',
    category: 'Manöver',
    definition: 'Omkopplare som kräver en fysisk nyckel för att ändra läge och förhindra obehörig manöver.',
    examples: ['Nyckelbrytare för serviceläge', 'Behörighetsväljare på maskinstyrning'],
    typicalPrefix: '-SC1',
    legacyComparison: 'Tidigare klass -S.',
    colorClass: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30',
  },
  {
    code: 'SE',
    mainClass: 'S',
    swedishName: 'Nödstoppsknapp (Manöverdon)',
    englishName: 'Emergency stop pushbutton',
    category: 'Manöver',
    definition: 'Röd svampformad tryckknapp med gul bakgrund som spärras i nedtryckt läge vid aktivering.',
    examples: ['Nödstoppsknapp med vridåterställning på skåpsdörr', 'Nödstopp tryck-dra vid maskin'],
    typicalPrefix: '-SE1',
    legacyComparison: 'Ofta betecknad -S eller -SB i äldre scheman.',
    colorClass: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30',
  },
  {
    code: 'SF',
    mainClass: 'S',
    swedishName: 'Fotpedal (Fotomkopplare)',
    englishName: 'Foot switch',
    category: 'Manöver',
    definition: 'Fotomkopplare som frigör operatörens händer för arbetsstycket vid start eller klämning.',
    examples: ['Fotpedal till kantpress', 'Fotomkopplare för svetsning'],
    typicalPrefix: '-SF1',
    legacyComparison: 'Tidigare klass -S.',
    colorClass: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30',
  },
  {
    code: 'SJ',
    mainClass: 'S',
    swedishName: 'Styrspak (Joystick / Traversdon)',
    englishName: 'Joystick / Coordinate switch',
    category: 'Manöver',
    definition: 'Manöverdon med spak som kan röras i en eller flera riktningar för steglös eller flerlägesstyrning.',
    examples: ['Styrspak till traverskran', 'Operatörsjoystick för maskinaxlar'],
    typicalPrefix: '-SJ1',
    legacyComparison: 'Tidigare klass -S.',
    colorClass: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30',
  },
  {
    code: 'SK',
    mainClass: 'S',
    swedishName: 'Gränslägesbrytare / Säkerhetsbrytare med mekanisk kontakt',
    englishName: 'Limit switch / Position switch',
    category: 'Manöver',
    definition: 'Mekanisk kontakt som aktiveras fysiskt när en rörlig maskindel eller dörr når ett visst läge.',
    examples: ['Ändlägesbrytare med rulle för lyftbord', 'Skyddsluckebrytare med säkerhetsbrytning'],
    typicalPrefix: '-SK1',
    legacyComparison: 'Betecknades ofta -S eller -SQ i äldre system.',
    colorClass: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30',
  },

  // --- KLASS T: Transformera energi eller information ---
  {
    code: 'TA',
    mainClass: 'T',
    swedishName: 'Strömtransformator (Mättransformator)',
    englishName: 'Current transformer (CT)',
    category: 'Transformering',
    definition: 'Mätransformator som transformerar ner hög primärström till standardiserad sekundärström (vanligen 5 A eller 1 A).',
    examples: ['Mätströmtransformator x/5A på inkommande fasskenor', 'Skyddsströmtransformator för reläskydd'],
    typicalPrefix: '-TA1 (L1), -TA2 (L2), -TA3 (L3)',
    legacyComparison: 'Klassisk standardbeteckning i ställverk och mätartavlor.',
    colorClass: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30',
  },
  {
    code: 'TB',
    mainClass: 'T',
    swedishName: 'Spänningstransformator (Mätransformator)',
    englishName: 'Voltage transformer (VT)',
    category: 'Transformering',
    definition: 'Mätransformator för att säkert transformera ner högspänning till mätbar lågspänning (t.ex. 110 V).',
    examples: ['Spänningstransformator för mellanspänningsmätning', 'Skyddsspänningstransformator'],
    typicalPrefix: '-TB1',
    legacyComparison: 'Tidigare klass -T.',
    colorClass: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30',
  },
  {
    code: 'TC',
    mainClass: 'T',
    swedishName: 'Krafttransformator / Distributionstransformator',
    englishName: 'Power transformer',
    category: 'Transformering',
    definition: 'Transformator för överföring och distribution av elektrisk kraft mellan spänningsnivåer med bibehållen frekvens.',
    examples: ['Distributionstransformator 10 kV / 400 V', 'Gjuthartstransformator i fastighetstransformatorrum'],
    typicalPrefix: '-TC1',
    legacyComparison: 'Kallades ofta -T i nätstationer.',
    colorClass: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30',
  },
  {
    code: 'TD',
    mainClass: 'T',
    swedishName: 'Manövertransformator / Skyddstransformator',
    englishName: 'Control transformer',
    category: 'Transformering',
    definition: 'Transformator i apparatskåp för att skapa galvaniskt skild manöverspänning (t.ex. 400V/230V eller 24V AC SELV/PELV).',
    examples: ['Manövertransformator 400V till 230V i apparatskåp', 'Klocktransformator 230V/12V', 'Skyddstransformator för våtrum'],
    typicalPrefix: '-TD1',
    legacyComparison: 'Standardkomponent i alla industriskåp.',
    colorClass: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30',
  },
  {
    code: 'TF',
    mainClass: 'T',
    swedishName: 'Frekvensomriktare (VFD)',
    englishName: 'Frequency converter / Variable frequency drive',
    category: 'Transformering',
    definition: 'Elektronisk apparat som omvandlar fast nätspänning och frekvens (400V 50Hz) till variabel spänning och frekvens för varvtalsstyrning av motorer.',
    examples: ['Frekvensomriktare för fläkt- och pumpstyrning (Danfoss, ABB, Schneider)', 'Vektorstyrd servoomriktare'],
    typicalPrefix: '-TF1',
    legacyComparison: 'Betecknades ofta -U, -G eller -FC i äldre ritningar.',
    colorClass: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30',
  },
  {
    code: 'TG',
    mainClass: 'T',
    swedishName: 'Växelriktare / Solcellsväxelriktare (Inverter)',
    englishName: 'Inverter (DC to AC)',
    category: 'Transformering',
    definition: 'Elektronisk apparat som omvandlar likspänning (DC) till sinusformad växelspänning (AC).',
    examples: ['Solcellsväxelriktare för nätanslutning (Fronius, SMA, Huawei)', 'Batteriväxelriktare för energilager'],
    typicalPrefix: '-TG1',
    legacyComparison: 'Tidigare klass -G eller -U.',
    colorClass: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30',
  },
  {
    code: 'TH',
    mainClass: 'T',
    swedishName: 'Likriktare (AC till DC)',
    englishName: 'Rectifier',
    category: 'Transformering',
    definition: 'Enhet som omvandlar växelström till likström.',
    examples: ['Diodbrygga', 'Tyristorstyrd likriktare för batteriladdning eller galvanisering'],
    typicalPrefix: '-TH1',
    legacyComparison: 'Tidigare klass -V eller -G.',
    colorClass: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30',
  },
  {
    code: 'TK',
    mainClass: 'T',
    swedishName: 'Signalsplitter / Mätomvandlare / Galvanisk isolator',
    englishName: 'Signal converter / Isolator',
    category: 'Transformering',
    definition: 'Omvandlar en elektrisk mätsignal till en annan normerad standard (t.ex. PT100 till 4-20 mA eller 0-10 V till 4-20 mA).',
    examples: ['Temperaturtransmitter för plintmontage', 'Galvanisk signalisolator', 'Normsignalsomvandlare'],
    typicalPrefix: '-TK1',
    legacyComparison: 'Tidigare betecknad -U eller -B.',
    colorClass: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30',
  },

  // --- KLASS P: Presentera information (Mätning & Indikering) ---
  {
    code: 'PA',
    mainClass: 'P',
    swedishName: 'Amperemeter (Strömmätare)',
    englishName: 'Ammeter',
    category: 'Mätning & Indikering',
    definition: 'Visarinstrument eller digitaldisplay för kontinuerlig avläsning av strömstyrka.',
    examples: ['Analog vridspoleamperemeter i ställverksdörr', 'Digital strömindikator'],
    typicalPrefix: '-PA1',
    legacyComparison: 'Klassisk beteckning på kretsscheman.',
    colorClass: 'text-pink-400 bg-pink-500/10 border-pink-500/30',
  },
  {
    code: 'PB',
    mainClass: 'P',
    swedishName: 'Voltmeter (Spänningsmätare)',
    englishName: 'Voltmeter',
    category: 'Mätning & Indikering',
    definition: 'Instrument för mätning och visning av elektrisk spänning.',
    examples: ['Panelvoltmeter 0-500 V', 'Digital spänningsdisplay'],
    typicalPrefix: '-PB1',
    legacyComparison: 'Tidigare klass -P.',
    colorClass: 'text-pink-400 bg-pink-500/10 border-pink-500/30',
  },
  {
    code: 'PC',
    mainClass: 'P',
    swedishName: 'Effektmätare / Energimätare (kWh-mätare / Nätanalysator)',
    englishName: 'Power meter / Energy meter',
    category: 'Mätning & Indikering',
    definition: 'Instrument för mätning och ackumulering av aktiv/reaktiv effekt och elenergi.',
    examples: ['MID-godkänd energimätare i central', 'Nätanalysator med Modbus/M-bus', 'Panelwattmeter'],
    typicalPrefix: '-PC1',
    legacyComparison: 'Mycket vanlig vid debitering och fastighetsstyrning.',
    colorClass: 'text-pink-400 bg-pink-500/10 border-pink-500/30',
  },
  {
    code: 'PJ',
    mainClass: 'P',
    swedishName: 'Akustisk signalgivare (Signalhorn / Siren / Summer)',
    englishName: 'Acoustic alarm / Horn / Siren / Buzzer',
    category: 'Mätning & Indikering',
    definition: 'Apparat som avger hörbar ljudsignal vid larm, driftstart eller fara.',
    examples: ['Larmsiren 24V vid brand/processfel', 'Summer i apparatskåp för kvittering', 'Signalhorn vid kranstart'],
    typicalPrefix: '-PJ1',
    legacyComparison: 'Betecknades ofta -H i äldre system.',
    colorClass: 'text-pink-400 bg-pink-500/10 border-pink-500/30',
  },
  {
    code: 'PL',
    mainClass: 'P',
    swedishName: 'Optisk signalgivare (Signallampa / Ljustorn / LED)',
    englishName: 'Optical indicator / Pilot light / Signal tower',
    category: 'Mätning & Indikering',
    definition: 'Visuell indikator som visar driftsläge, spänningsnärvaro eller larm med ljus.',
    examples: ['Grön driftslampa (Normal drift)', 'Röd fellampa (Larm / Trippsäkring)', 'Ljustorn röd/gul/grön på maskin', 'Spänningsindikator på skåpsdörr'],
    typicalPrefix: '-PL1 (ofta även -H1 i svensk installationspraxis)',
    legacyComparison: 'Mycket vanligt betecknad -H eller -HL i äldre elscheman!',
    colorClass: 'text-pink-400 bg-pink-500/10 border-pink-500/30',
  },
  {
    code: 'PU',
    mainClass: 'P',
    swedishName: 'Bildskärm / Operatörspanel (HMI / Display)',
    englishName: 'Display / Touchscreen / HMI panel',
    category: 'Mätning & Indikering',
    definition: 'Grafisk pekskärm eller monitor för operatörsinteraktion och processvisualisering.',
    examples: ['Pekskärm i skåpsdörr (t.ex. Siemens Comfort Panel, Beijer)', 'Textdisplay på regulator'],
    typicalPrefix: '-PU1',
    legacyComparison: 'Betecknades ofta -OP eller -U.',
    colorClass: 'text-pink-400 bg-pink-500/10 border-pink-500/30',
  },

  // --- KLASS X: Anslutning och förbindning ---
  {
    code: 'XB',
    mainClass: 'X',
    swedishName: 'Radplint / Kopplingsplint (DIN-plint)',
    englishName: 'Terminal block / Terminal strip',
    category: 'Anslutning',
    definition: 'Modulär kopplingsplint för fastskruvning eller push-in anslutning av externa kablar och intern kablage.',
    examples: ['Skruvplint eller push-in plint på DIN-skena (Phoenix, Weidmüller, Wago)', 'Frånskiljbar nollplint', 'Skyddsledarplint PE'],
    typicalPrefix: '-XB1 eller :X1 (Plintrad 1)',
    legacyComparison: 'I scheman betecknas hela plintraden vanligen -X1, -X2 osv.',
    colorClass: 'text-teal-400 bg-teal-500/10 border-teal-500/30',
  },
  {
    code: 'XC',
    mainClass: 'X',
    swedishName: 'Vägguttag / Skåpsuttag / CEE-uttag',
    englishName: 'Socket-outlet',
    category: 'Anslutning',
    definition: 'Fast anslutet don avsett för tillfällig anslutning av flyttbara förbrukare via stickpropp.',
    examples: ['Serviceuttag 230V Schuko i apparatskåp', 'CEE-uttag 400V 16A/32A trefas på vägg'],
    typicalPrefix: '-XC1',
    legacyComparison: 'Tidigare klass -X.',
    colorClass: 'text-teal-400 bg-teal-500/10 border-teal-500/30',
  },
  {
    code: 'XD',
    mainClass: 'X',
    swedishName: 'Stickpropp / Apparatintag (CEE-don)',
    englishName: 'Plug / Appliance inlet',
    category: 'Anslutning',
    definition: 'Flyttbart anslutningsdon med stift för anslutning i uttag.',
    examples: ['CEE-stickpropp 3-fas', 'Schuko-stickpropp med kabel'],
    typicalPrefix: '-XD1',
    legacyComparison: 'Tidigare klass -X.',
    colorClass: 'text-teal-400 bg-teal-500/10 border-teal-500/30',
  },
  {
    code: 'XE',
    mainClass: 'X',
    swedishName: 'Jordplint / Huvudjordningsskena (HJS / PE)',
    englishName: 'Earthing terminal / Ground bar',
    category: 'Anslutning',
    definition: 'Central samlingspunkt för skyddsjordning och potentialutjämning.',
    examples: ['Huvudjordningsskena (HJS) i elcentral', 'PE-plintskena', 'Potentialutjämningsskena (PUS)'],
    typicalPrefix: '-XE1 (eller PE-skena)',
    legacyComparison: 'Mycket viktig för elinstallationskontroll.',
    colorClass: 'text-teal-400 bg-teal-500/10 border-teal-500/30',
  },
  {
    code: 'XJ',
    mainClass: 'X',
    swedishName: 'Flerpoligt industridon (Harting m.fl.)',
    englishName: 'Multi-pin connector / Heavy duty connector',
    category: 'Anslutning',
    definition: 'Robust snabbanslutningsdon för snabb isärkoppling av hela kabelstammar mellan skåp och maskinmoduler.',
    examples: ['Harting Han-don (16-pol, 24-pol)', 'M12 runda sensorkontaktdon', 'Ventilkontakter Form A/B'],
    typicalPrefix: '-XJ1',
    legacyComparison: 'Ofta betecknad -X eller -XS i maskiner.',
    colorClass: 'text-teal-400 bg-teal-500/10 border-teal-500/30',
  },

  // --- KLASS W: Kablar och ledare ---
  {
    code: 'WA',
    mainClass: 'W',
    swedishName: 'Kraftkabel / Matarkabel',
    englishName: 'Power cable / Feeder cable',
    category: 'Kablar & Ledare',
    definition: 'Isolerad flerledarkabel för överföring av elektrisk kraft till undercentraler eller laster.',
    examples: ['Matarkabel FXQJ / N1XV / EXQ', 'Skärmad motorkabel för frekvensomriktardrift (Top Cable)'],
    typicalPrefix: '-WA1 (eller W1)',
    legacyComparison: 'Standardbeteckning för kablar i kabellistor.',
    colorClass: 'text-orange-400 bg-orange-500/10 border-orange-500/30',
  },
  {
    code: 'WB',
    mainClass: 'W',
    swedishName: 'Styrkabel / Manöverkabel',
    englishName: 'Control cable',
    category: 'Kablar & Ledare',
    definition: 'Flerledarkabel för överföring av styrsignaler och digitala signaler.',
    examples: ['Skärmad styrkabel (ÖLFLEX Classic, LiYCY)', 'Sensorkabel 4x0.34 mm²'],
    typicalPrefix: '-WB1',
    legacyComparison: 'Betecknades ofta -W.',
    colorClass: 'text-orange-400 bg-orange-500/10 border-orange-500/30',
  },
  {
    code: 'WC',
    mainClass: 'W',
    swedishName: 'Busskabel / Datakabel (Ethernet / Modbus / CAN)',
    englishName: 'Data / Fieldbus cable',
    category: 'Kablar & Ledare',
    definition: 'Högfrekvenskabel med partvinnade ledare och skärmning för digital industriell kommunikation.',
    examples: ['Grön industriell Ethernet-kabel (Cat6A / Profinet)', 'Lila Profibus DP-kabel', 'Partvinnad RS-485 Modbus-kabel'],
    typicalPrefix: '-WC1',
    legacyComparison: 'Tidigare klass -W.',
    colorClass: 'text-orange-400 bg-orange-500/10 border-orange-500/30',
  },
  {
    code: 'WD',
    mainClass: 'W',
    swedishName: 'Optisk fiberkabel',
    englishName: 'Optical fiber cable',
    category: 'Kablar & Ledare',
    definition: 'Kabel innehållande glas- eller plastfibrer för ljusbaserad störningsfri datakommunikation.',
    examples: ['Multimode eller Singlemode fiberkabel mellan ställverk och kontrollrum'],
    typicalPrefix: '-WD1',
    legacyComparison: 'Tidigare klass -W.',
    colorClass: 'text-orange-400 bg-orange-500/10 border-orange-500/30',
  },
  {
    code: 'WE',
    mainClass: 'W',
    swedishName: 'Fasskena / Samlingsskena (Kopparskena)',
    englishName: 'Busbar / Phase bus',
    category: 'Kablar & Ledare',
    definition: 'Oisolerad eller isolerad metallskena (koppar eller aluminium) med låg resistans för hög strömfördelning.',
    examples: ['Fasskenor L1, L2, L3 i huvudfördelning', 'Fasskena för dvärgbrytare i normcentral (gaffelskena/pinnskena)'],
    typicalPrefix: '-WE1',
    legacyComparison: 'Kallades ofta samlingsskena eller skensystem.',
    colorClass: 'text-orange-400 bg-orange-500/10 border-orange-500/30',
  },
  {
    code: 'WG',
    mainClass: 'W',
    swedishName: 'Skyddsledare / Potentialutjämningsledare',
    englishName: 'Protective conductor (PE)',
    category: 'Kablar & Ledare',
    definition: 'Ledare avsedd för skyddsändamål, t.ex. skyddsjordning mot elchock eller skyddspotentialutjämning.',
    examples: ['Gul/grön PE-kabel', 'Kopparlina 16–50 mm² för grundpotentialutjämning'],
    typicalPrefix: '-WG1',
    legacyComparison: 'Märks alltid PE i elinstallationer.',
    colorClass: 'text-orange-400 bg-orange-500/10 border-orange-500/30',
  },

  // --- KLASS G: Initiera energiflöde / Kraftkällor ---
  {
    code: 'GA',
    mainClass: 'G',
    swedishName: 'Generator (Reservkraftsaggregat / Dieselgenerator)',
    englishName: 'Generator',
    category: 'Kraftkällor',
    definition: 'Roterande maskin som omvandlar mekanisk rörelse (från t.ex. dieselmotor eller turbin) till elektrisk ström.',
    examples: ['Synkrongenerator i reservkraftaggregat på sjukhus', 'Småskalig vattenkraftgenerator'],
    typicalPrefix: '-GA1',
    legacyComparison: 'Tidigare klass -G.',
    colorClass: 'text-lime-400 bg-lime-500/10 border-lime-500/30',
  },
  {
    code: 'GB',
    mainClass: 'G',
    swedishName: 'Solcellspanel (PV-modul / Sträng)',
    englishName: 'Photovoltaic panel / Solar generator',
    category: 'Kraftkällor',
    definition: 'Halvledaranordning som omvandlar solens ljusenergi direkt till likström via den fotovoltaiska effekten.',
    examples: ['Solcellspaneler på tak', 'PV-sträng till solcellsväxelriktare'],
    typicalPrefix: '-GB1',
    legacyComparison: 'Tidigare klass -G.',
    colorClass: 'text-lime-400 bg-lime-500/10 border-lime-500/30',
  },
  {
    code: 'GC',
    mainClass: 'G',
    swedishName: 'Nätaggregat (Strömförsörjning 24V DC)',
    englishName: 'Power supply unit (PSU)',
    category: 'Kraftkällor',
    definition: 'Spänningsaggregat som levererar stabiliserad likspänning till styrsystem och PLC.',
    examples: ['Switchat DIN-skeneaggregat 230VAC till 24VDC (t.ex. Phoenix Quint, Puls, Mean Well)'],
    typicalPrefix: '-GC1',
    legacyComparison: 'Mycket vanligt i alla apparatskåp, ersätter gamla -G.',
    colorClass: 'text-lime-400 bg-lime-500/10 border-lime-500/30',
  },
  {
    code: 'GE',
    mainClass: 'G',
    swedishName: 'UPS (Avbrottsfri kraftförsörjning)',
    englishName: 'Uninterruptible power supply (UPS)',
    category: 'Kraftkällor',
    definition: 'Apparatsystem som vid nätavbrott omedelbart levererar reservström från ackumulatorbatterier utan spänningsdipp.',
    examples: ['Rackmonterad UPS för serverrum', '24V DC buffertmodul med ultrakondensatorer'],
    typicalPrefix: '-GE1',
    legacyComparison: 'Tidigare klass -G.',
    colorClass: 'text-lime-400 bg-lime-500/10 border-lime-500/30',
  },

  // --- KLASS E: Värme och belysning ---
  {
    code: 'EA',
    mainClass: 'E',
    swedishName: 'Belysningsarmatur / LED-belysning',
    englishName: 'Luminaire / Lighting fixture',
    category: 'Värme & Ljus',
    definition: 'Elektrisk anordning som producerar synligt ljus för upplysning av lokaler eller maskiner.',
    examples: ['LED-panel i undertak', 'Industriarmatur IP65 i verkstad', 'Nödbelysning med batteribackup', 'Apparatskåpsbelysning'],
    typicalPrefix: '-EA1 (eller E1)',
    legacyComparison: 'Kallades ofta -E i elinstallationsritningar.',
    colorClass: 'text-amber-300 bg-amber-400/10 border-amber-400/30',
  },
  {
    code: 'EB',
    mainClass: 'E',
    swedishName: 'Värmeelement / Elpatron / Värmekabel',
    englishName: 'Electric heater / Heating element',
    category: 'Värme & Ljus',
    definition: 'Resistiv komponent avsedd att omvandla elektrisk energi till ren värmeenergi.',
    examples: ['Elpatron 6 kW i ackumulatortank', 'Självbegränsande värmekabel för frostskydd av rör', 'Skåpvärmare med termostat'],
    typicalPrefix: '-EB1',
    legacyComparison: 'Tidigare ofta betecknad -E eller -R.',
    colorClass: 'text-amber-300 bg-amber-400/10 border-amber-400/30',
  },

  // --- KLASS R: Begränsa eller stabilisera ---
  {
    code: 'RA',
    mainClass: 'R',
    swedishName: 'Resistor / Fast motstånd',
    englishName: 'Resistor',
    category: 'Begränsning',
    definition: 'Elektrisk tvåpol med specificerad resistans för att begränsa ström eller skapa spänningsfall.',
    examples: ['Förkopplingsmotstånd', 'Dämpmotstånd'],
    typicalPrefix: '-RA1',
    legacyComparison: 'Klassisk beteckning -R.',
    colorClass: 'text-stone-300 bg-stone-500/10 border-stone-500/30',
  },
  {
    code: 'RB',
    mainClass: 'R',
    swedishName: 'Mätshunt (Strömshunt)',
    englishName: 'Current shunt',
    category: 'Begränsning',
    definition: 'Precisionsmotstånd med mycket låg resistans över vilket ett proportionellt millivolt-spänningsfall mäts.',
    examples: ['Mätshunt 60 mV för DC-strömmätning i likströmsfördelning'],
    typicalPrefix: '-RB1',
    legacyComparison: 'Tidigare klass -R.',
    colorClass: 'text-stone-300 bg-stone-500/10 border-stone-500/30',
  },
  {
    code: 'RC',
    mainClass: 'R',
    swedishName: 'Potentiometer (Ställbart motstånd)',
    englishName: 'Potentiometer',
    category: 'Begränsning',
    definition: 'Vridbart eller skjutbart variabelt motstånd för manuell inställning av börvärde eller hastighet.',
    examples: ['Börvärdespotentiometer på skåpsdörr till frekvensomriktare'],
    typicalPrefix: '-RC1',
    legacyComparison: 'Tidigare klass -R.',
    colorClass: 'text-stone-300 bg-stone-500/10 border-stone-500/30',
  },
  {
    code: 'RD',
    mainClass: 'R',
    swedishName: 'Diod / Frihjulsdiod',
    englishName: 'Diode',
    category: 'Begränsning',
    definition: 'Halvledare som leder ström i en riktning och spärrar i den andra, t.ex. för att släcka induktiva spänningstoppar vid reläspolar.',
    examples: ['Frihjulsdiod över kontaktorspole (släckdiod)', 'Backdiod i solcellskoppling'],
    typicalPrefix: '-RD1',
    legacyComparison: 'Betecknades ofta -V i äldre ritningar.',
    colorClass: 'text-stone-300 bg-stone-500/10 border-stone-500/30',
  },
  {
    code: 'RE',
    mainClass: 'R',
    swedishName: 'Bromsmotstånd',
    englishName: 'Braking resistor',
    category: 'Begränsning',
    definition: 'Effekttåligt motstånd för att förbränna regenerativ kinetisk energi som värme vid inbromsning av elmotorer.',
    examples: ['Externt bromsmotstånd kopplat till frekvensomriktarens DC-mellanled vid hiss- eller traversdrift'],
    typicalPrefix: '-RE1',
    legacyComparison: 'Mycket vanligt i lyft- och transportapplikationer.',
    colorClass: 'text-stone-300 bg-stone-500/10 border-stone-500/30',
  },
  {
    code: 'RF',
    mainClass: 'R',
    swedishName: 'EMC-filter / Nätfilter / Avstörningsfilter',
    englishName: 'EMC filter / Power line filter',
    category: 'Begränsning',
    definition: 'Kombinerat filter (induktanser och kondensatorer) för att dämpa högfrekventa störningar på nätledningen.',
    examples: ['Nätfilter före frekvensomriktare för att uppfylla EMC-direktivet'],
    typicalPrefix: '-RF1',
    legacyComparison: 'Tidigare klass -Z eller -R.',
    colorClass: 'text-stone-300 bg-stone-500/10 border-stone-500/30',
  },
  {
    code: 'RL',
    mainClass: 'R',
    swedishName: 'Reaktor / Drossel / Induktans',
    englishName: 'Inductor / Choke / Reactor',
    category: 'Begränsning',
    definition: 'Spole som begränsar strömändringshastighet eller övertoner genom induktiv reaktans.',
    examples: ['Nätglättningsreaktor (drossel)', 'Kompareringsdrossel'],
    typicalPrefix: '-RL1',
    legacyComparison: 'Kallades ofta -L i äldre elteknik.',
    colorClass: 'text-stone-300 bg-stone-500/10 border-stone-500/30',
  },
  {
    code: 'RN',
    mainClass: 'R',
    swedishName: 'Varistor (VDR)',
    englishName: 'Varistor',
    category: 'Begränsning',
    definition: 'Icke-linjärt motstånd vars resistans faller kraftigt vid spänningsspikar för att skydda komponenter.',
    examples: ['Gnistssläckare över reläspole', 'Inbyggt överspänningsskydd på kretskort'],
    typicalPrefix: '-RN1',
    legacyComparison: 'Tidigare klass -R.',
    colorClass: 'text-stone-300 bg-stone-500/10 border-stone-500/30',
  },
  {
    code: 'RZ',
    mainClass: 'R',
    swedishName: 'Termineringsmotstånd (Bussterminator)',
    englishName: 'Termination resistor',
    category: 'Begränsning',
    definition: 'Ändmotstånd i databussar för att förhindra signalreflektioner vid kabeländar.',
    examples: ['120 Ω ändmotstånd i RS-485 / Modbus / CAN-buss', 'Profibus busstermineringskontakt'],
    typicalPrefix: '-RZ1',
    legacyComparison: 'Kritisk komponent för stabil kommunikation.',
    colorClass: 'text-stone-300 bg-stone-500/10 border-stone-500/30',
  },

  // --- KLASS C: Lagra energi eller information ---
  {
    code: 'CA',
    mainClass: 'C',
    swedishName: 'Kondensator / Faskompensering',
    englishName: 'Capacitor',
    category: 'Energilagring',
    definition: 'Passiv tvåpolig komponent som lagrar elektrisk energi i ett elektrostatiskt fält.',
    examples: ['Faskompenseringskondensator i ställverk', 'Start-/driftkondensator för enfasmotor', 'Glättningskondensator i likriktare'],
    typicalPrefix: '-CA1',
    legacyComparison: 'Klassisk beteckning -C.',
    colorClass: 'text-blue-300 bg-blue-500/10 border-blue-500/30',
  },
  {
    code: 'CB',
    mainClass: 'C',
    swedishName: 'Ackumulator / Batteri',
    englishName: 'Battery / Accumulator',
    category: 'Energilagring',
    definition: 'Kemisk lagringsenhet som avger elektricitet för reservkraft och backup.',
    examples: ['Blybatteribank för ställverksmanöver 110V DC', 'Litiumjon-batteripack i energilager', 'Backupbatteri på PLC-processor'],
    typicalPrefix: '-CB1',
    legacyComparison: 'Betecknades ofta -G eller -B i äldre system.',
    colorClass: 'text-blue-300 bg-blue-500/10 border-blue-500/30',
  },

  // --- KLASS U: Hålla objekt i definierat läge (Kapsling & Stativ) ---
  {
    code: 'UA',
    mainClass: 'U',
    swedishName: 'Apparatskåp / Kapsling / Elcentral',
    englishName: 'Enclosure / Cabinet',
    category: 'Kapsling & Stativ',
    definition: 'Fysisk struktur som skyddar elektriska komponenter mot yttre påverkan och hindrar oavsiktlig beröring.',
    examples: ['Golvstående apparatskåp i stålplåt (Rittal m.fl.)', 'Normkapsling för väggmontage', 'Kopplingslåda i polyester/polykarbonat'],
    typicalPrefix: '=A1 +W1 (Skåpsbeteckning)',
    legacyComparison: 'Betecknas vanligen i platsprefixet `+W1` eller `+AS1`.',
    colorClass: 'text-slate-300 bg-slate-500/10 border-slate-500/30',
  },
  {
    code: 'UB',
    mainClass: 'U',
    swedishName: '19-tums rack / Stativ',
    englishName: 'Mounting rack',
    category: 'Kapsling & Stativ',
    definition: 'Standardiserat metallramverk för montering av serverutrustning, automation eller ställverk.',
    examples: ['19-tums rackskåp för nätverk och servrar', 'Stativ för frekvensomriktare'],
    typicalPrefix: '+UB1',
    legacyComparison: 'Tidigare platsmärkning.',
    colorClass: 'text-slate-300 bg-slate-500/10 border-slate-500/30',
  },
  {
    code: 'UC',
    mainClass: 'U',
    swedishName: 'Kabelstege / Trådstege / Kabelränna',
    englishName: 'Cable tray / Cable ladder',
    category: 'Kapsling & Stativ',
    definition: 'Mekaniskt stödsystem för bärande och dragning av kablage i byggnader och industrier.',
    examples: ['Kabelstege MP-bolagen / Wibe', 'Trådstege under innertak', 'Perforerad plåtränna'],
    typicalPrefix: '+UC1',
    legacyComparison: 'Standard i byggnadsinformationsmodeller (BIM).',
    colorClass: 'text-slate-300 bg-slate-500/10 border-slate-500/30',
  },
  {
    code: 'UD',
    mainClass: 'U',
    swedishName: 'DIN-skena / Montageskena',
    englishName: 'Mounting rail / DIN rail',
    category: 'Kapsling & Stativ',
    definition: 'Standardiserad 35 mm stålskena för snabbfäste av moduler, reläer och plintar i elcentraler.',
    examples: ['Top-hat DIN-skena 35x7.5 mm', 'C-profilskena för fästbyglar'],
    typicalPrefix: '-UD1',
    legacyComparison: 'Universal i europeisk elbyggnad.',
    colorClass: 'text-slate-300 bg-slate-500/10 border-slate-500/30',
  },
];

export interface IecPrefixRule {
  symbol: string;
  name: string;
  englishAspect: string;
  purpose: string;
  example: string;
  explanation: string;
}

export const IEC_PREFIX_RULES: IecPrefixRule[] = [
  {
    symbol: '=',
    name: 'Funktion (Function aspect)',
    englishAspect: 'Function',
    purpose: 'Identifierar vilket delsystem, processavsnitt eller övergripande funktion komponenten tillhör.',
    example: '=P1 eller =VENT1',
    explanation: '=P1 anger t.ex. Processavsnitt Pumpstation 1, eller =VENT1 för Ventilationsaggregat 1.',
  },
  {
    symbol: '+',
    name: 'Placering (Location aspect)',
    englishAspect: 'Location',
    purpose: 'Identifierar den fysiska installationsplatsen, t.ex. apparatskåp, rum eller maskinposition.',
    example: '+W1 eller +RUM102',
    explanation: '+W1 anger apparatskåp 1. Komponenter märkta +W1 sitter fysiskt inne i eller på skåp 1.',
  },
  {
    symbol: '-',
    name: 'Produkt / Komponent (Product aspect)',
    englishAspect: 'Product',
    purpose: 'Den unika referensbeteckningen / postbeteckningen för den specifika elektriska komponenten enligt IEC 81346-2.',
    example: '-QA1 eller -KM1 eller -BT1',
    explanation: '-QA1 är t.ex. huvudströmbrytaren i skåpet; -BT1 är temperaturgivaren.',
  },
  {
    symbol: ':',
    name: 'Anslutningspunkt / Klämma (Terminal aspect)',
    englishAspect: 'Terminal',
    purpose: 'Identifierar den specifika elektriska anslutningsklämman, plintnumret eller stiftet på komponenten.',
    example: ':13, :14 eller :A1, :A2',
    explanation: '-KM1:A1 anger anslutningsklämma A1 på spolen till kontaktor -KM1.',
  },
];

/**
 * Filter function to search across IEC 81346 Table 2 entries
 */
export function searchIec81346(
  query: string,
  selectedCategory: string = 'Alla',
  selectedMainClass: string = 'Alla'
): Iec81346Entry[] {
  const cleanQuery = query.trim().toLowerCase();

  return IEC_TABLE_2_ENTRIES.filter((entry) => {
    // 1. Category match
    if (selectedCategory !== 'Alla' && entry.category !== selectedCategory) {
      return false;
    }

    // 2. Main class match
    if (selectedMainClass !== 'Alla' && entry.mainClass !== selectedMainClass) {
      return false;
    }

    // 3. Text query match
    if (!cleanQuery) return true;

    // Direct code match (e.g. "QA", "qa", "q", "f")
    if (entry.code.toLowerCase() === cleanQuery) return true;
    if (entry.code.toLowerCase().includes(cleanQuery)) return true;
    if (entry.typicalPrefix.toLowerCase().includes(cleanQuery)) return true;

    // Swedish and English names
    if (entry.swedishName.toLowerCase().includes(cleanQuery)) return true;
    if (entry.englishName.toLowerCase().includes(cleanQuery)) return true;

    // Definition
    if (entry.definition.toLowerCase().includes(cleanQuery)) return true;

    // Real-world examples (e.g. "dvärgbrytare", "kontaktor", "pt100", "nödstopp")
    const matchInExamples = entry.examples.some((ex) =>
      ex.toLowerCase().includes(cleanQuery)
    );
    if (matchInExamples) return true;

    // Legacy comparison
    if (entry.legacyComparison && entry.legacyComparison.toLowerCase().includes(cleanQuery)) {
      return true;
    }

    return false;
  });
}
